import type {
  Alert,
  Call,
  CallAnalysis,
  CoachingItem,
  Deal,
  Insight,
  Organisation,
  Playbook,
  Team,
  TimelineMarker,
  TranscriptSegment,
  User,
} from "@/lib/demo/types";

export const ORG_ID = "org-apex";

export const organisation: Organisation = {
  id: ORG_ID,
  name: "Apex Markets",
  industry: "Forex & financial services",
  timezone: "Europe/Nicosia",
  settings: {
    languages: ["en", "el"],
    recordingConsentRequired: true,
    retentionDays: 365,
  },
  createdAt: "2025-11-01T00:00:00.000Z",
};

export const users: User[] = [
  {
    id: "u-01",
    organisationId: ORG_ID,
    teamId: "team-forex",
    role: "manager",
    name: "Alex Moreau",
    email: "alex.moreau@apexmarkets.demo",
    status: "active",
    title: "Forex Desk Manager",
    createdAt: "2025-11-02T00:00:00.000Z",
  },
  {
    id: "u-02",
    organisationId: ORG_ID,
    teamId: "team-forex",
    role: "representative",
    name: "Priya Nair",
    email: "priya.nair@apexmarkets.demo",
    status: "active",
    title: "Senior Broker",
    createdAt: "2025-11-03T00:00:00.000Z",
  },
  {
    id: "u-03",
    organisationId: ORG_ID,
    teamId: "team-forex",
    role: "representative",
    name: "Elena Christou",
    email: "elena.christou@apexmarkets.demo",
    status: "active",
    title: "Broker",
    createdAt: "2025-11-04T00:00:00.000Z",
  },
  {
    id: "u-04",
    organisationId: ORG_ID,
    teamId: "team-forex",
    role: "representative",
    name: "Andreas Papas",
    email: "andreas.papas@apexmarkets.demo",
    status: "active",
    title: "Broker",
    createdAt: "2025-11-05T00:00:00.000Z",
  },
  {
    id: "u-05",
    organisationId: ORG_ID,
    teamId: "team-forex",
    role: "representative",
    name: "Omar Haddad",
    email: "omar.haddad@apexmarkets.demo",
    status: "active",
    title: "Broker",
    createdAt: "2025-11-06T00:00:00.000Z",
  },
  {
    id: "u-06",
    organisationId: ORG_ID,
    teamId: "team-wealth",
    role: "manager",
    name: "Lena Fischer",
    email: "lena.fischer@apexmarkets.demo",
    status: "active",
    title: "Wealth Team Lead",
    createdAt: "2025-11-07T00:00:00.000Z",
  },
  {
    id: "u-07",
    organisationId: ORG_ID,
    teamId: "team-wealth",
    role: "representative",
    name: "Nadia Petrova",
    email: "nadia.petrova@apexmarkets.demo",
    status: "active",
    title: "Advisor",
    createdAt: "2025-11-08T00:00:00.000Z",
  },
  {
    id: "u-08",
    organisationId: ORG_ID,
    teamId: "team-realty",
    role: "manager",
    name: "Tom Beckett",
    email: "tom.beckett@apexmarkets.demo",
    status: "active",
    title: "Real Estate Lead",
    createdAt: "2025-11-09T00:00:00.000Z",
  },
  {
    id: "u-09",
    organisationId: ORG_ID,
    teamId: "team-realty",
    role: "representative",
    name: "Diego Ramos",
    email: "diego.ramos@apexmarkets.demo",
    status: "active",
    title: "Agent",
    createdAt: "2025-11-10T00:00:00.000Z",
  },
  {
    id: "u-10",
    organisationId: ORG_ID,
    teamId: "team-wealth",
    role: "representative",
    name: "Sara Kim",
    email: "sara.kim@apexmarkets.demo",
    status: "active",
    title: "Advisor",
    createdAt: "2025-11-11T00:00:00.000Z",
  },
  {
    id: "u-11",
    organisationId: ORG_ID,
    teamId: "team-forex",
    role: "representative",
    name: "Maya Costa",
    email: "maya.costa@apexmarkets.demo",
    status: "active",
    title: "Broker",
    createdAt: "2025-12-01T00:00:00.000Z",
  },
  {
    id: "u-12",
    organisationId: ORG_ID,
    teamId: "team-wealth",
    role: "representative",
    name: "Jonas Berg",
    email: "jonas.berg@apexmarkets.demo",
    status: "active",
    title: "Advisor",
    createdAt: "2025-12-02T00:00:00.000Z",
  },
  {
    id: "u-13",
    organisationId: ORG_ID,
    teamId: "team-realty",
    role: "representative",
    name: "Aisha Rahman",
    email: "aisha.rahman@apexmarkets.demo",
    status: "active",
    title: "Agent",
    createdAt: "2025-12-03T00:00:00.000Z",
  },
  {
    id: "u-disabled",
    organisationId: ORG_ID,
    teamId: "team-forex",
    role: "representative",
    name: "Disabled User",
    email: "disabled@apexmarkets.demo",
    status: "disabled",
    title: "Broker",
    createdAt: "2025-11-01T00:00:00.000Z",
  },
  {
    id: "u-exec",
    organisationId: ORG_ID,
    teamId: "team-forex",
    role: "executive",
    name: "Maya Okonkwo",
    email: "maya.okonkwo@apexmarkets.demo",
    status: "active",
    title: "Chief Revenue Officer",
    createdAt: "2025-11-01T00:00:00.000Z",
  },
  {
    id: "u-admin",
    organisationId: ORG_ID,
    teamId: "team-forex",
    role: "admin",
    name: "Jordan Ellis",
    email: "jordan.ellis@apexmarkets.demo",
    status: "active",
    title: "Organisation Administrator",
    createdAt: "2025-11-01T00:00:00.000Z",
  },
  {
    id: "u-dir",
    organisationId: ORG_ID,
    teamId: "team-forex",
    role: "director",
    name: "Chris Antonou",
    email: "chris.antonou@apexmarkets.demo",
    status: "active",
    title: "Sales Director",
    createdAt: "2025-11-01T00:00:00.000Z",
  },
];

export const teams: Team[] = [
  {
    id: "team-forex",
    organisationId: ORG_ID,
    managerId: "u-01",
    name: "Forex Desk",
    office: "Nicosia",
  },
  {
    id: "team-wealth",
    organisationId: ORG_ID,
    managerId: "u-06",
    name: "Wealth & Insurance",
    office: "Limassol",
  },
  {
    id: "team-realty",
    organisationId: ORG_ID,
    managerId: "u-08",
    name: "Real Estate",
    office: "Larnaca",
  },
];

/** 25 opportunities — values used by pipeline + risk KPIs */
type DealBase = Omit<
  Deal,
  | "conversationHealth"
  | "lastInteraction"
  | "riskReasons"
  | "stakeholders"
  | "crmSyncStatus"
  | "irisRecommendation"
>;

const dealBases: DealBase[] = [
  {
    id: "d-01",
    organisationId: ORG_ID,
    representativeId: "u-01",
    teamId: "team-forex",
    accountName: "Feldman Capital",
    title: "Liquidity package",
    stage: "Closed won",
    value: 84000,
    currency: "EUR",
    expectedCloseDate: "2026-07-30",
    riskLevel: "Low",
    forecastConfidence: 96,
    nextStep: "Onboarding kickoff",
    crmSource: "HubSpot",
  },
  {
    id: "d-02",
    organisationId: ORG_ID,
    representativeId: "u-02",
    teamId: "team-forex",
    accountName: "Meridian FX",
    title: "Prime account",
    stage: "Proposal",
    value: 62000,
    currency: "EUR",
    expectedCloseDate: "2026-08-12",
    riskLevel: "High",
    forecastConfidence: 42,
    nextStep: "Revisit value before price",
    crmSource: "HubSpot",
  },
  {
    id: "d-03",
    organisationId: ORG_ID,
    representativeId: "u-08",
    teamId: "team-realty",
    accountName: "Northgate Realty",
    title: "Agency tools",
    stage: "Discovery",
    value: 41000,
    currency: "EUR",
    expectedCloseDate: "2026-08-28",
    riskLevel: "Medium",
    forecastConfidence: 58,
    nextStep: "Book stakeholder call",
    crmSource: "HubSpot",
  },
  {
    id: "d-04",
    organisationId: ORG_ID,
    representativeId: "u-06",
    teamId: "team-wealth",
    accountName: "Aurora Insurance",
    title: "Advisor suite",
    stage: "Negotiation",
    value: 28000,
    currency: "EUR",
    expectedCloseDate: "2026-08-05",
    riskLevel: "High",
    forecastConfidence: 38,
    nextStep: "Competitor comparison pack",
    crmSource: "Salesforce",
  },
  {
    id: "d-05",
    organisationId: ORG_ID,
    representativeId: "u-05",
    teamId: "team-forex",
    accountName: "Vault Trading",
    title: "DMA access",
    stage: "Proposal",
    value: 55000,
    currency: "EUR",
    expectedCloseDate: "2026-08-18",
    riskLevel: "Medium",
    forecastConfidence: 55,
    nextStep: "Lock calendar commitment",
    crmSource: "HubSpot",
  },
  {
    id: "d-06",
    organisationId: ORG_ID,
    representativeId: "u-07",
    teamId: "team-wealth",
    accountName: "Harbor Wealth",
    title: "Private clients",
    stage: "Closed won",
    value: 112000,
    currency: "EUR",
    expectedCloseDate: "2026-07-28",
    riskLevel: "Low",
    forecastConfidence: 98,
    nextStep: "Contract countersign",
    crmSource: "Salesforce",
  },
  {
    id: "d-07",
    organisationId: ORG_ID,
    representativeId: "u-04",
    teamId: "team-forex",
    accountName: "Crescent Brokers",
    title: "White label",
    stage: "Follow-up",
    value: 73000,
    currency: "EUR",
    expectedCloseDate: "2026-08-22",
    riskLevel: "Medium",
    forecastConfidence: 61,
    nextStep: "Send execution SLA",
    crmSource: "HubSpot",
  },
  {
    id: "d-08",
    organisationId: ORG_ID,
    representativeId: "u-10",
    teamId: "team-wealth",
    accountName: "Kestrel Recruitment",
    title: "Benefits plan",
    stage: "Qualified",
    value: 19000,
    currency: "EUR",
    expectedCloseDate: "2026-09-01",
    riskLevel: "Low",
    forecastConfidence: 72,
    nextStep: "Needs workshop",
    crmSource: "HubSpot",
  },
  {
    id: "d-09",
    organisationId: ORG_ID,
    representativeId: "u-03",
    teamId: "team-forex",
    accountName: "BluePeak Capital",
    title: "Swap account",
    stage: "Proposal",
    value: 47000,
    currency: "EUR",
    expectedCloseDate: "2026-08-14",
    riskLevel: "High",
    forecastConfidence: 35,
    nextStep: "Address pricing hesitation",
    crmSource: "HubSpot",
  },
  {
    id: "d-10",
    organisationId: ORG_ID,
    representativeId: "u-09",
    teamId: "team-realty",
    accountName: "Seaside Homes",
    title: "Listing package",
    stage: "Negotiation",
    value: 33000,
    currency: "EUR",
    expectedCloseDate: "2026-08-09",
    riskLevel: "Medium",
    forecastConfidence: 64,
    nextStep: "Site visit follow-up",
    crmSource: "Pipedrive",
  },
  {
    id: "d-11",
    organisationId: ORG_ID,
    representativeId: "u-02",
    teamId: "team-forex",
    accountName: "Orion Desk",
    title: "ECN upgrade",
    stage: "Closed won",
    value: 96000,
    currency: "EUR",
    expectedCloseDate: "2026-07-22",
    riskLevel: "Low",
    forecastConfidence: 97,
    nextStep: "Tech onboarding",
    crmSource: "HubSpot",
  },
  {
    id: "d-12",
    organisationId: ORG_ID,
    representativeId: "u-01",
    teamId: "team-forex",
    accountName: "Helios Prop",
    title: "Prop firm flow",
    stage: "Discovery",
    value: 88000,
    currency: "EUR",
    expectedCloseDate: "2026-09-10",
    riskLevel: "Low",
    forecastConfidence: 70,
    nextStep: "Volume discovery",
    crmSource: "HubSpot",
  },
  {
    id: "d-13",
    organisationId: ORG_ID,
    representativeId: "u-07",
    teamId: "team-wealth",
    accountName: "Nordic Pensions",
    title: "Advisory seat",
    stage: "Proposal",
    value: 67000,
    currency: "EUR",
    expectedCloseDate: "2026-08-30",
    riskLevel: "High",
    forecastConfidence: 40,
    nextStep: "Decision-maker meeting",
    crmSource: "Salesforce",
  },
  {
    id: "d-14",
    organisationId: ORG_ID,
    representativeId: "u-04",
    teamId: "team-forex",
    accountName: "Atlas Liquidity",
    title: "Backup LP",
    stage: "Follow-up",
    value: 51000,
    currency: "EUR",
    expectedCloseDate: "2026-08-16",
    riskLevel: "Medium",
    forecastConfidence: 57,
    nextStep: "Trial credentials",
    crmSource: "HubSpot",
  },
  {
    id: "d-15",
    organisationId: ORG_ID,
    representativeId: "u-08",
    teamId: "team-realty",
    accountName: "Cityline Estates",
    title: "CRM + dialer",
    stage: "Closed won",
    value: 45000,
    currency: "EUR",
    expectedCloseDate: "2026-07-18",
    riskLevel: "Low",
    forecastConfidence: 95,
    nextStep: "Training schedule",
    crmSource: "Pipedrive",
  },
  {
    id: "d-16",
    organisationId: ORG_ID,
    representativeId: "u-05",
    teamId: "team-forex",
    accountName: "RedSand FX",
    title: "Retail book",
    stage: "Lost",
    value: 39000,
    currency: "EUR",
    expectedCloseDate: "2026-07-25",
    riskLevel: "High",
    forecastConfidence: 10,
    nextStep: "Post-mortem",
    crmSource: "HubSpot",
  },
  {
    id: "d-17",
    organisationId: ORG_ID,
    representativeId: "u-03",
    teamId: "team-forex",
    accountName: "Ionian Markets",
    title: "MT5 bridge",
    stage: "Qualified",
    value: 58000,
    currency: "EUR",
    expectedCloseDate: "2026-08-25",
    riskLevel: "Low",
    forecastConfidence: 74,
    nextStep: "Technical workshop",
    crmSource: "HubSpot",
  },
  {
    id: "d-18",
    organisationId: ORG_ID,
    representativeId: "u-10",
    teamId: "team-wealth",
    accountName: "Silverline Advisors",
    title: "Model portfolios",
    stage: "Discovery",
    value: 24000,
    currency: "EUR",
    expectedCloseDate: "2026-09-05",
    riskLevel: "Medium",
    forecastConfidence: 52,
    nextStep: "Risk questionnaire",
    crmSource: "Salesforce",
  },
  {
    id: "d-19",
    organisationId: ORG_ID,
    representativeId: "u-06",
    teamId: "team-wealth",
    accountName: "Peninsula Life",
    title: "Protection suite",
    stage: "Proposal",
    value: 71000,
    currency: "EUR",
    expectedCloseDate: "2026-08-20",
    riskLevel: "High",
    forecastConfidence: 36,
    nextStep: "Address compliance concern",
    crmSource: "Salesforce",
  },
  {
    id: "d-20",
    organisationId: ORG_ID,
    representativeId: "u-09",
    teamId: "team-realty",
    accountName: "Harbor View Props",
    title: "Agent seats",
    stage: "Follow-up",
    value: 27000,
    currency: "EUR",
    expectedCloseDate: "2026-08-11",
    riskLevel: "Medium",
    forecastConfidence: 60,
    nextStep: "Send pricing sheet",
    crmSource: "Pipedrive",
  },
  {
    id: "d-21",
    organisationId: ORG_ID,
    representativeId: "u-02",
    teamId: "team-forex",
    accountName: "Quantum Flow",
    title: "Latency SLA",
    stage: "Negotiation",
    value: 102000,
    currency: "EUR",
    expectedCloseDate: "2026-08-07",
    riskLevel: "Low",
    forecastConfidence: 78,
    nextStep: "Legal review",
    crmSource: "HubSpot",
  },
  {
    id: "d-22",
    organisationId: ORG_ID,
    representativeId: "u-01",
    teamId: "team-forex",
    accountName: "Cyprus Desk Co",
    title: "Desk expansion",
    stage: "Discovery",
    value: 64000,
    currency: "EUR",
    expectedCloseDate: "2026-09-15",
    riskLevel: "Low",
    forecastConfidence: 68,
    nextStep: "Multi-desk demo",
    crmSource: "HubSpot",
  },
  {
    id: "d-23",
    organisationId: ORG_ID,
    representativeId: "u-07",
    teamId: "team-wealth",
    accountName: "Amber Family Office",
    title: "Discretionary",
    stage: "Closed won",
    value: 128000,
    currency: "EUR",
    expectedCloseDate: "2026-07-15",
    riskLevel: "Low",
    forecastConfidence: 99,
    nextStep: "KYC complete",
    crmSource: "Salesforce",
  },
  {
    id: "d-24",
    organisationId: ORG_ID,
    representativeId: "u-04",
    teamId: "team-forex",
    accountName: "Delta Spreads",
    title: "Rebate plan",
    stage: "Proposal",
    value: 44000,
    currency: "EUR",
    expectedCloseDate: "2026-08-19",
    riskLevel: "High",
    forecastConfidence: 33,
    nextStep: "Value-before-price coaching",
    crmSource: "HubSpot",
  },
  {
    id: "d-25",
    organisationId: ORG_ID,
    representativeId: "u-08",
    teamId: "team-realty",
    accountName: "Olive Branch Realty",
    title: "Team licence",
    stage: "Qualified",
    value: 36000,
    currency: "EUR",
    expectedCloseDate: "2026-08-27",
    riskLevel: "Low",
    forecastConfidence: 71,
    nextStep: "Pilot with 3 agents",
    crmSource: "Pipedrive",
  },
];

function enrichDeal(d: DealBase): Deal {
  const health =
    d.riskLevel === "High"
      ? "Critical"
      : d.riskLevel === "Medium"
        ? "At risk"
        : d.stage === "Closed won"
          ? "Strong"
          : "Stable";
  const reasons: Deal["riskReasons"] =
    d.riskLevel === "High"
      ? ["Pricing hesitation", "Decision-maker absent"]
      : d.riskLevel === "Medium"
        ? ["Weak urgency", "No agreed next step"]
        : [];
  if (/compliance/i.test(d.nextStep)) reasons.push("Compliance concern");
  if (/competitor/i.test(d.nextStep)) reasons.push("Competitor evaluation");
  return {
    ...d,
    conversationHealth: health,
    lastInteraction: d.expectedCloseDate < "2026-07-20" ? "2026-07-10" : "2026-07-28",
    riskReasons: [...new Set(reasons)],
    stakeholders: d.riskLevel === "High" ? ["Champion"] : ["Champion", "Economic buyer"],
    crmSyncStatus: d.crmSource === "Pipedrive" ? "Needs mapping" : "Synced",
    irisRecommendation: d.nextStep,
  };
}

export const deals: Deal[] = dealBases.map(enrichDeal);

type CallSeed = Omit<Call, "organisationId" | "externalId" | "source" | "recordingUrl"> & {
  analysis: Omit<CallAnalysis, "id" | "callId" | "organisationId">;
  externalId?: string | null;
  source?: Call["source"];
  recordingUrl?: string | null;
};

function iso(day: string, time: string) {
  return `${day}T${time}:00.000Z`;
}

const callSeeds: CallSeed[] = [
  {
    id: "c-1841",
    teamId: "team-forex",
    representativeId: "u-01",
    dealId: "d-01",
    prospect: "Marcus Feldman",
    company: "Feldman Capital",
    startedAt: iso("2026-07-30", "09:12"),
    durationSec: 862,
    language: "en",
    callType: "Outbound",
    outcome: "Closed",
    analysisStatus: "Analyzed",
    coachingStatus: "Completed",
    reviewed: true,
    analysis: baseAnalysis(
      92,
      "Positive",
      "Low",
      ["Strong discovery", "Clear next step"],
      ["Minor talk-ratio drift"],
      ["Send onboarding pack"],
      ["pricing"],
      [],
      ["Kickoff Thursday"],
    ),
  },
  {
    id: "c-1840",
    teamId: "team-forex",
    representativeId: "u-02",
    dealId: "d-02",
    prospect: "Yara Haddad",
    company: "Meridian FX",
    startedAt: iso("2026-07-30", "10:04"),
    durationSec: 527,
    language: "en",
    callType: "Outbound",
    outcome: "Follow-up",
    analysisStatus: "Analyzed",
    coachingStatus: "Assigned",
    reviewed: false,
    analysis: baseAnalysis(
      78,
      "Mixed",
      "High",
      ["Rapport"],
      ["Priced before discovery", "Weak objection handle"],
      ["Assign Value Before Price"],
      ["pricing", "spreads"],
      ["Competitor X"],
      ["Callback Friday"],
    ),
  },
  {
    id: "c-1839",
    teamId: "team-realty",
    representativeId: "u-08",
    dealId: "d-03",
    prospect: "Daniel Okoye",
    company: "Northgate Realty",
    startedAt: iso("2026-07-30", "10:52"),
    durationSec: 1263,
    language: "en",
    callType: "Discovery",
    outcome: "Qualified",
    analysisStatus: "Analyzed",
    coachingStatus: "Pending",
    reviewed: true,
    analysis: baseAnalysis(
      85,
      "Neutral",
      "Medium",
      ["Good qualification"],
      ["Decision-maker absent"],
      ["Book stakeholder"],
      ["timeline"],
      [],
      ["Stakeholder call"],
    ),
  },
  {
    id: "c-1838",
    teamId: "team-wealth",
    representativeId: "u-06",
    dealId: "d-04",
    prospect: "Sofia Lindqvist",
    company: "Aurora Insurance",
    startedAt: iso("2026-07-29", "16:31"),
    durationSec: 375,
    language: "en",
    callType: "Outbound",
    outcome: "Lost",
    analysisStatus: "Analyzed",
    coachingStatus: "Assigned",
    reviewed: true,
    analysis: baseAnalysis(
      61,
      "Negative",
      "High",
      [],
      ["Talked over prospect", "No next step", "Competitor preference"],
      ["Roleplay competitor objection"],
      ["price", "incumbent"],
      ["RivalCo"],
      [],
    ),
  },
  {
    id: "c-1837",
    teamId: "team-forex",
    representativeId: "u-05",
    dealId: "d-05",
    prospect: "Peter Almeida",
    company: "Vault Trading",
    startedAt: iso("2026-07-29", "14:08"),
    durationSec: 704,
    language: "en",
    callType: "Follow-up",
    outcome: "Closed",
    analysisStatus: "Analyzed",
    coachingStatus: "None",
    reviewed: true,
    analysis: baseAnalysis(
      89,
      "Positive",
      "Medium",
      ["Listening", "Closing clarity"],
      ["Slight urgency gap"],
      ["Confirm DMA timeline"],
      [],
      [],
      ["Signed order form"],
    ),
  },
  {
    id: "c-1836",
    teamId: "team-wealth",
    representativeId: "u-10",
    dealId: "d-08",
    prospect: "Hana Ito",
    company: "Kestrel Recruitment",
    startedAt: iso("2026-07-29", "11:22"),
    durationSec: 182,
    language: "en",
    callType: "Outbound",
    outcome: "No answer",
    analysisStatus: "Processing",
    coachingStatus: "None",
    reviewed: false,
    analysis: emptyAnalysis(),
  },
  {
    id: "c-1835",
    teamId: "team-forex",
    representativeId: "u-04",
    dealId: "d-07",
    prospect: "Ali Rahman",
    company: "Crescent Brokers",
    startedAt: iso("2026-07-28", "15:47"),
    durationSec: 1076,
    language: "en",
    callType: "Outbound",
    outcome: "Follow-up",
    analysisStatus: "Analyzed",
    coachingStatus: "Pending",
    reviewed: false,
    analysis: baseAnalysis(
      74,
      "Mixed",
      "Medium",
      ["Product knowledge"],
      ["Pricing early", "Missed compliance disclosure"],
      ["Review disclosure checklist"],
      ["pricing"],
      [],
      ["Send SLA"],
    ),
  },
  {
    id: "c-1834",
    teamId: "team-wealth",
    representativeId: "u-07",
    dealId: "d-06",
    prospect: "Grace Whitfield",
    company: "Harbor Wealth",
    startedAt: iso("2026-07-28", "09:58"),
    durationSec: 758,
    language: "en",
    callType: "Outbound",
    outcome: "Closed",
    analysisStatus: "Analyzed",
    coachingStatus: "Completed",
    reviewed: true,
    analysis: baseAnalysis(
      94,
      "Positive",
      "Low",
      ["Consultative discovery", "Playbook adherence"],
      [],
      ["Share as best-call example"],
      [],
      [],
      ["Countersign today"],
    ),
  },
  {
    id: "c-1833",
    teamId: "team-forex",
    representativeId: "u-03",
    dealId: "d-09",
    prospect: "Nikos Georgiou",
    company: "BluePeak Capital",
    startedAt: iso("2026-07-28", "13:10"),
    durationSec: 640,
    language: "el",
    callType: "Outbound",
    outcome: "Follow-up",
    analysisStatus: "Analyzed",
    coachingStatus: "Assigned",
    reviewed: false,
    analysis: baseAnalysis(
      68,
      "Mixed",
      "High",
      ["Language fluency"],
      ["Pricing before value", "Weak discovery"],
      ["Value Before Price playbook"],
      ["pricing"],
      ["BrokerOne"],
      ["Demo Thursday"],
    ),
  },
  {
    id: "c-1832",
    teamId: "team-realty",
    representativeId: "u-09",
    dealId: "d-10",
    prospect: "Maria Costa",
    company: "Seaside Homes",
    startedAt: iso("2026-07-27", "16:05"),
    durationSec: 890,
    language: "en",
    callType: "Inbound",
    outcome: "Follow-up",
    analysisStatus: "Analyzed",
    coachingStatus: "Pending",
    reviewed: true,
    analysis: baseAnalysis(
      76,
      "Neutral",
      "Medium",
      ["Empathy"],
      ["No urgency established"],
      ["Create urgency exercise"],
      ["timing"],
      [],
      ["Site visit"],
    ),
  },
  {
    id: "c-1831",
    teamId: "team-forex",
    representativeId: "u-02",
    dealId: "d-11",
    prospect: "James Whit",
    company: "Orion Desk",
    startedAt: iso("2026-07-27", "11:40"),
    durationSec: 980,
    language: "en",
    callType: "Outbound",
    outcome: "Closed",
    analysisStatus: "Analyzed",
    coachingStatus: "Completed",
    reviewed: true,
    analysis: baseAnalysis(
      91,
      "Positive",
      "Low",
      ["Objection handling", "Next-step discipline"],
      [],
      ["Document winning phrases"],
      ["latency"],
      [],
      ["Tech kickoff"],
    ),
  },
  {
    id: "c-1830",
    teamId: "team-forex",
    representativeId: "u-01",
    dealId: "d-12",
    prospect: "Leila Hassan",
    company: "Helios Prop",
    startedAt: iso("2026-07-27", "09:20"),
    durationSec: 1120,
    language: "en",
    callType: "Discovery",
    outcome: "Qualified",
    analysisStatus: "Analyzed",
    coachingStatus: "None",
    reviewed: true,
    analysis: baseAnalysis(
      88,
      "Positive",
      "Low",
      ["Deep discovery"],
      ["Could confirm budget earlier"],
      ["Ask volume band earlier"],
      ["volume"],
      [],
      ["Volume workshop"],
    ),
  },
  {
    id: "c-1829",
    teamId: "team-wealth",
    representativeId: "u-07",
    dealId: "d-13",
    prospect: "Erik Lund",
    company: "Nordic Pensions",
    startedAt: iso("2026-07-26", "14:55"),
    durationSec: 720,
    language: "en",
    callType: "Outbound",
    outcome: "Follow-up",
    analysisStatus: "Analyzed",
    coachingStatus: "Assigned",
    reviewed: false,
    analysis: baseAnalysis(
      70,
      "Mixed",
      "High",
      ["Structure"],
      ["Decision-maker absent", "Low urgency"],
      ["Multi-thread stakeholders"],
      ["procurement"],
      ["LegacyVendor"],
      [],
    ),
  },
  {
    id: "c-1828",
    teamId: "team-forex",
    representativeId: "u-04",
    dealId: "d-14",
    prospect: "Samir Khan",
    company: "Atlas Liquidity",
    startedAt: iso("2026-07-26", "10:15"),
    durationSec: 845,
    language: "en",
    callType: "Follow-up",
    outcome: "Follow-up",
    analysisStatus: "Analyzed",
    coachingStatus: "Pending",
    reviewed: true,
    analysis: baseAnalysis(
      79,
      "Neutral",
      "Medium",
      ["Technical clarity"],
      ["No calendar hold"],
      ["Always book next step live"],
      [],
      [],
      ["Trial credentials"],
    ),
  },
  {
    id: "c-1827",
    teamId: "team-realty",
    representativeId: "u-08",
    dealId: "d-15",
    prospect: "Olivia Grant",
    company: "Cityline Estates",
    startedAt: iso("2026-07-25", "15:30"),
    durationSec: 910,
    language: "en",
    callType: "Outbound",
    outcome: "Closed",
    analysisStatus: "Analyzed",
    coachingStatus: "Completed",
    reviewed: true,
    analysis: baseAnalysis(
      90,
      "Positive",
      "Low",
      ["Closing", "Playbook"],
      [],
      ["Add to best-call library"],
      [],
      [],
      ["Training schedule"],
    ),
  },
  {
    id: "c-1826",
    teamId: "team-forex",
    representativeId: "u-05",
    dealId: "d-16",
    prospect: "Victor Chen",
    company: "RedSand FX",
    startedAt: iso("2026-07-25", "12:05"),
    durationSec: 510,
    language: "en",
    callType: "Outbound",
    outcome: "Lost",
    analysisStatus: "Analyzed",
    coachingStatus: "Assigned",
    reviewed: true,
    analysis: baseAnalysis(
      54,
      "Negative",
      "High",
      [],
      ["Interrupted heavily", "Priced immediately", "No discovery"],
      ["Discovery fundamentals training"],
      ["pricing"],
      ["CheapBroker"],
      [],
    ),
  },
  {
    id: "c-1825",
    teamId: "team-forex",
    representativeId: "u-03",
    dealId: "d-17",
    prospect: "Eleni Markou",
    company: "Ionian Markets",
    startedAt: iso("2026-07-24", "16:40"),
    durationSec: 990,
    language: "el",
    callType: "Discovery",
    outcome: "Qualified",
    analysisStatus: "Analyzed",
    coachingStatus: "None",
    reviewed: true,
    analysis: baseAnalysis(
      84,
      "Positive",
      "Low",
      ["Discovery depth"],
      ["Slightly long monologue"],
      ["Tighten pitch timing"],
      ["integration"],
      [],
      ["Technical workshop"],
    ),
  },
  {
    id: "c-1824",
    teamId: "team-wealth",
    representativeId: "u-10",
    dealId: "d-18",
    prospect: "Paul Rivers",
    company: "Silverline Advisors",
    startedAt: iso("2026-07-24", "11:05"),
    durationSec: 670,
    language: "en",
    callType: "Inbound",
    outcome: "Qualified",
    analysisStatus: "Analyzed",
    coachingStatus: "Pending",
    reviewed: false,
    analysis: baseAnalysis(
      81,
      "Neutral",
      "Medium",
      ["Listening"],
      ["Budget vague"],
      ["Clarify budget signals"],
      ["risk"],
      [],
      ["Risk questionnaire"],
    ),
  },
  {
    id: "c-1823",
    teamId: "team-wealth",
    representativeId: "u-06",
    dealId: "d-19",
    prospect: "Amira Said",
    company: "Peninsula Life",
    startedAt: iso("2026-07-23", "14:20"),
    durationSec: 780,
    language: "en",
    callType: "Outbound",
    outcome: "Follow-up",
    analysisStatus: "Analyzed",
    coachingStatus: "Assigned",
    reviewed: true,
    analysis: baseAnalysis(
      66,
      "Mixed",
      "High",
      ["Empathy"],
      ["Compliance concern unresolved", "Pricing hesitation"],
      ["Compliance script + value"],
      ["compliance", "pricing"],
      [],
      ["Compliance FAQ send"],
    ),
  },
  {
    id: "c-1822",
    teamId: "team-realty",
    representativeId: "u-09",
    dealId: "d-20",
    prospect: "Helen Brooks",
    company: "Harbor View Props",
    startedAt: iso("2026-07-23", "09:50"),
    durationSec: 600,
    language: "en",
    callType: "Follow-up",
    outcome: "Follow-up",
    analysisStatus: "Analyzed",
    coachingStatus: "None",
    reviewed: false,
    analysis: baseAnalysis(
      73,
      "Neutral",
      "Medium",
      ["Persistence"],
      ["No clear next step on call"],
      ["Confirm next step verbally"],
      ["price"],
      [],
      ["Send pricing sheet"],
    ),
  },
  {
    id: "c-1821",
    teamId: "team-forex",
    representativeId: "u-02",
    dealId: "d-21",
    prospect: "Ryan Cole",
    company: "Quantum Flow",
    startedAt: iso("2026-07-22", "15:15"),
    durationSec: 1050,
    language: "en",
    callType: "Outbound",
    outcome: "Follow-up",
    analysisStatus: "Analyzed",
    coachingStatus: "Completed",
    reviewed: true,
    analysis: baseAnalysis(
      87,
      "Positive",
      "Low",
      ["Technical credibility", "Mutual plan"],
      [],
      ["Keep legal loop tight"],
      ["latency"],
      [],
      ["Legal review"],
    ),
  },
  {
    id: "c-1820",
    teamId: "team-forex",
    representativeId: "u-01",
    dealId: "d-22",
    prospect: "Christina Demetriou",
    company: "Cyprus Desk Co",
    startedAt: iso("2026-07-22", "10:35"),
    durationSec: 820,
    language: "el",
    callType: "Discovery",
    outcome: "Qualified",
    analysisStatus: "Analyzed",
    coachingStatus: "None",
    reviewed: true,
    analysis: baseAnalysis(
      86,
      "Positive",
      "Low",
      ["Multi-desk framing"],
      [],
      ["Prepare expansion ROI one-pager"],
      ["expansion"],
      [],
      ["Multi-desk demo"],
    ),
  },
  {
    id: "c-1819",
    teamId: "team-wealth",
    representativeId: "u-07",
    dealId: "d-23",
    prospect: "Isabelle Moreau",
    company: "Amber Family Office",
    startedAt: iso("2026-07-21", "13:45"),
    durationSec: 940,
    language: "en",
    callType: "Outbound",
    outcome: "Closed",
    analysisStatus: "Analyzed",
    coachingStatus: "Completed",
    reviewed: true,
    analysis: baseAnalysis(
      95,
      "Positive",
      "Low",
      ["Trust building", "Closing quality"],
      [],
      ["Capture winning phrases"],
      [],
      [],
      ["KYC complete"],
    ),
  },
  {
    id: "c-1818",
    teamId: "team-forex",
    representativeId: "u-04",
    dealId: "d-24",
    prospect: "Ben Ortiz",
    company: "Delta Spreads",
    startedAt: iso("2026-07-21", "11:00"),
    durationSec: 560,
    language: "en",
    callType: "Outbound",
    outcome: "Follow-up",
    analysisStatus: "Analyzed",
    coachingStatus: "Assigned",
    reviewed: false,
    analysis: baseAnalysis(
      63,
      "Mixed",
      "High",
      [],
      ["Price-led opener", "Weak discovery"],
      ["Value Before Price"],
      ["pricing", "rebates"],
      ["SpreadKing"],
      ["Value workshop"],
    ),
  },
  {
    id: "c-1817",
    teamId: "team-realty",
    representativeId: "u-08",
    dealId: "d-25",
    prospect: "George Elias",
    company: "Olive Branch Realty",
    startedAt: iso("2026-07-20", "16:25"),
    durationSec: 700,
    language: "en",
    callType: "Discovery",
    outcome: "Qualified",
    analysisStatus: "Analyzed",
    coachingStatus: "None",
    reviewed: true,
    analysis: baseAnalysis(
      82,
      "Positive",
      "Low",
      ["Pilot framing"],
      ["Could quantify ROI earlier"],
      ["Add ROI calculator"],
      ["adoption"],
      [],
      ["3-agent pilot"],
    ),
  },
  {
    id: "c-1816",
    teamId: "team-forex",
    representativeId: "u-05",
    dealId: "d-05",
    prospect: "Peter Almeida",
    company: "Vault Trading",
    startedAt: iso("2026-07-20", "10:10"),
    durationSec: 480,
    language: "en",
    callType: "Outbound",
    outcome: "Follow-up",
    analysisStatus: "Analyzed",
    coachingStatus: "Assigned",
    reviewed: true,
    analysis: baseAnalysis(
      59,
      "Mixed",
      "Medium",
      [],
      ["Interruptions", "Filler-heavy", "No next step"],
      ["Listening drills"],
      ["dma"],
      [],
      [],
    ),
  },
  {
    id: "c-1815",
    teamId: "team-forex",
    representativeId: "u-03",
    dealId: "d-09",
    prospect: "Nikos Georgiou",
    company: "BluePeak Capital",
    startedAt: iso("2026-07-18", "14:00"),
    durationSec: 615,
    language: "el",
    callType: "Follow-up",
    outcome: "Follow-up",
    analysisStatus: "Analyzed",
    coachingStatus: "Pending",
    reviewed: false,
    analysis: baseAnalysis(
      71,
      "Mixed",
      "High",
      ["Persistence"],
      ["Repeated pricing objection"],
      ["Objection library practice"],
      ["pricing"],
      ["BrokerOne"],
      ["Internal sponsor chat"],
    ),
  },
  {
    id: "c-1814",
    teamId: "team-wealth",
    representativeId: "u-10",
    dealId: "d-08",
    prospect: "Hana Ito",
    company: "Kestrel Recruitment",
    startedAt: iso("2026-07-18", "09:30"),
    durationSec: 730,
    language: "en",
    callType: "Outbound",
    outcome: "Qualified",
    analysisStatus: "Analyzed",
    coachingStatus: "None",
    reviewed: true,
    analysis: baseAnalysis(
      80,
      "Positive",
      "Low",
      ["Needs analysis"],
      [],
      ["Prep benefits workshop"],
      ["benefits"],
      [],
      ["Needs workshop"],
    ),
  },
  {
    id: "c-1813",
    teamId: "team-forex",
    representativeId: "u-02",
    dealId: "d-02",
    prospect: "Yara Haddad",
    company: "Meridian FX",
    startedAt: iso("2026-07-17", "15:50"),
    durationSec: 690,
    language: "en",
    callType: "Discovery",
    outcome: "Qualified",
    analysisStatus: "Analyzed",
    coachingStatus: "Completed",
    reviewed: true,
    analysis: baseAnalysis(
      83,
      "Neutral",
      "High",
      ["Discovery questions"],
      ["Did not confirm authority"],
      ["Authority check"],
      ["volume"],
      [],
      ["Authority confirmed later"],
    ),
  },
  {
    id: "c-1812",
    teamId: "team-realty",
    representativeId: "u-09",
    dealId: "d-10",
    prospect: "Maria Costa",
    company: "Seaside Homes",
    startedAt: iso("2026-07-16", "12:40"),
    durationSec: 540,
    language: "en",
    callType: "Outbound",
    outcome: "Follow-up",
    analysisStatus: "Analyzed",
    coachingStatus: "Pending",
    reviewed: false,
    analysis: baseAnalysis(
      69,
      "Mixed",
      "Medium",
      [],
      ["Weak urgency", "Missed next step"],
      ["Urgency + next-step drill"],
      ["timing"],
      [],
      [],
    ),
  },
  {
    id: "c-1811",
    teamId: "team-wealth",
    representativeId: "u-06",
    dealId: "d-04",
    prospect: "Sofia Lindqvist",
    company: "Aurora Insurance",
    startedAt: iso("2026-07-15", "10:00"),
    durationSec: 800,
    language: "en",
    callType: "Discovery",
    outcome: "Qualified",
    analysisStatus: "Analyzed",
    coachingStatus: "Completed",
    reviewed: true,
    analysis: baseAnalysis(
      77,
      "Neutral",
      "High",
      ["Structure"],
      ["Competitor not explored"],
      ["Competitor battlecard"],
      ["coverage"],
      ["RivalCo"],
      ["Needs map"],
    ),
  },
  {
    id: "c-1810",
    teamId: "team-forex",
    representativeId: "u-01",
    dealId: "d-01",
    prospect: "Marcus Feldman",
    company: "Feldman Capital",
    startedAt: iso("2026-07-14", "11:25"),
    durationSec: 760,
    language: "en",
    callType: "Discovery",
    outcome: "Qualified",
    analysisStatus: "Analyzed",
    coachingStatus: "Completed",
    reviewed: true,
    analysis: baseAnalysis(
      88,
      "Positive",
      "Low",
      ["Pain quantification"],
      [],
      ["Reuse discovery arc"],
      ["audit"],
      [],
      ["Proposal meeting"],
    ),
  },
];

function emptyAnalysis(): Omit<CallAnalysis, "id" | "callId" | "organisationId"> {
  return {
    overallScore: 0,
    discoveryScore: 0,
    listeningScore: 0,
    confidenceScore: 0,
    pitchScore: 0,
    objectionHandlingScore: 0,
    closingScore: 0,
    playbookScore: 0,
    sentiment: "Neutral",
    talkRatio: 0,
    interruptions: 0,
    strengths: [],
    weaknesses: [],
    recommendations: [],
    topics: [],
    objections: [],
    competitors: [],
    nextSteps: [],
    risks: [],
    dealIntel: {
      buyerNeeds: [],
      painPoints: [],
      objections: [],
      decisionCriteria: [],
      competitors: [],
      budgetSignals: "Unknown",
      urgency: "Unknown",
      stakeholders: [],
      agreedNextStep: "None",
      riskLevel: "Low",
    },
  };
}

function baseAnalysis(
  overall: number,
  sentiment: CallAnalysis["sentiment"],
  risk: CallAnalysis["dealIntel"]["riskLevel"],
  strengths: string[],
  weaknesses: string[],
  recommendations: string[],
  objections: string[],
  competitors: string[],
  nextSteps: string[],
): Omit<CallAnalysis, "id" | "callId" | "organisationId"> {
  const jitter = (n: number, d: number) => Math.max(0, Math.min(100, n + d));
  return {
    overallScore: overall,
    discoveryScore: jitter(overall, -6),
    listeningScore: jitter(overall, overall > 80 ? 2 : -10),
    confidenceScore: jitter(overall, 1),
    pitchScore: jitter(overall, -3),
    objectionHandlingScore: jitter(
      overall,
      weaknesses.some((w) => /objection|priced|price/i.test(w)) ? -12 : 2,
    ),
    closingScore: jitter(overall, nextSteps.length ? 4 : -8),
    playbookScore: jitter(overall, -2),
    sentiment,
    talkRatio: overall > 85 ? 52 : overall > 70 ? 64 : 78,
    interruptions: overall > 85 ? 1 : overall > 70 ? 3 : 6,
    strengths: strengths.map((text, i) => ({ text, timestampSec: 40 + i * 55 })),
    weaknesses: weaknesses.map((text, i) => ({ text, timestampSec: 120 + i * 70 })),
    recommendations,
    topics: ["discovery", "pricing", "next steps"].slice(0, 2 + (overall % 2)),
    objections,
    competitors,
    nextSteps,
    risks: weaknesses.slice(0, 2),
    dealIntel: {
      buyerNeeds: strengths.length ? ["Reliable execution", "Clear commercial terms"] : ["Unclear"],
      painPoints: weaknesses.length ? weaknesses.slice(0, 2) : ["None captured"],
      objections,
      decisionCriteria: ["Cost", "Latency", "Support"],
      competitors,
      budgetSignals: overall > 80 ? "Budget range discussed" : "Budget unclear",
      urgency: risk === "High" ? "Low / unclear" : "Medium",
      stakeholders: risk === "High" ? ["Champion only"] : ["Champion", "Economic buyer"],
      agreedNextStep: nextSteps[0] ?? "None",
      riskLevel: risk,
    },
  };
}

export const calls: Call[] = callSeeds.map(({ analysis: _a, ...c }) => ({
  ...c,
  organisationId: ORG_ID,
  externalId: c.externalId ?? `ext-${c.id}`,
  source: c.source ?? "demo",
  recordingUrl: c.recordingUrl ?? null,
}));

export const analyses: CallAnalysis[] = callSeeds.map(({ id, analysis }) => ({
  ...analysis,
  id: `an-${id}`,
  callId: id,
  organisationId: ORG_ID,
}));

export const analysisByCallId = Object.fromEntries(analyses.map((a) => [a.callId, a]));

/** Shared transcript template — specialized per call in getters */
export function buildTranscript(call: Call): TranscriptSegment[] {
  const rep = users.find((u) => u.id === call.representativeId)?.name ?? "Representative";
  const a = analysisByCallId[call.id];
  if (!a || call.analysisStatus !== "Analyzed") return [];

  const segments: Omit<TranscriptSegment, "id" | "organisationId">[] = [
    {
      callId: call.id,
      speaker: "rep",
      speakerName: rep,
      startTime: 0,
      endTime: 18,
      text: `Hi ${call.prospect.split(" ")[0]}, this is ${rep.split(" ")[0]} from Apex Markets — thanks for taking the time today.`,
      sentiment: "Positive",
      tags: [],
    },
    {
      callId: call.id,
      speaker: "prospect",
      speakerName: call.prospect,
      startTime: 18,
      endTime: 42,
      text: "Sure. We're evaluating options and need to understand how you compare on cost and reliability.",
      sentiment: "Neutral",
      tags: ["pricing"],
    },
    {
      callId: call.id,
      speaker: "rep",
      speakerName: rep,
      startTime: 42,
      endTime: 95,
      text:
        a.discoveryScore >= 80
          ? "Before numbers — how many lots are you averaging monthly, and what breaks when execution slips?"
          : "Our pricing is very competitive. Most clients see spreads within 0.2 of their current provider.",
      sentiment: a.discoveryScore >= 80 ? "Positive" : "Mixed",
      tags: a.discoveryScore >= 80 ? [] : ["pricing"],
    },
    {
      callId: call.id,
      speaker: "prospect",
      speakerName: call.prospect,
      startTime: 95,
      endTime: 140,
      text:
        a.objections[0] === "pricing" ||
        a.objections.includes("pricing") ||
        a.objections.includes("spreads")
          ? "Your spreads look higher than what we get today with our primary."
          : "That makes sense. We also need the decision committee involved.",
      sentiment: "Mixed",
      tags: a.objections.length ? ["objection", "pricing"] : [],
    },
    {
      callId: call.id,
      speaker: "rep",
      speakerName: rep,
      startTime: 140,
      endTime: 210,
      text:
        a.objectionHandlingScore >= 80
          ? "Understood — what are you paying per lot today? If we're within 0.2 but fill quality improves, does the maths still work against us?"
          : "We're pretty competitive actually — most clients don't mind the difference.",
      sentiment: a.objectionHandlingScore >= 80 ? "Positive" : "Negative",
      tags: a.objectionHandlingScore >= 80 ? ["objection"] : ["objection", "negative"],
    },
    {
      callId: call.id,
      speaker: "prospect",
      speakerName: call.prospect,
      startTime: 210,
      endTime: 250,
      text: a.competitors[0]
        ? `We're also speaking with ${a.competitors[0]}.`
        : "I need to loop in my partner before we commit.",
      sentiment: "Neutral",
      tags: a.competitors[0] ? ["competitor"] : [],
    },
    {
      callId: call.id,
      speaker: "rep",
      speakerName: rep,
      startTime: 250,
      endTime: 320,
      text:
        a.nextSteps.length > 0
          ? `Let's lock ${a.nextSteps[0]} so we keep momentum — does Thursday still work?`
          : "Okay, feel free to call me when you've decided.",
      sentiment: a.nextSteps.length ? "Positive" : "Negative",
      tags: a.nextSteps.length ? ["next_step"] : ["negative"],
    },
    {
      callId: call.id,
      speaker: "prospect",
      speakerName: call.prospect,
      startTime: 320,
      endTime: 350,
      text: a.nextSteps.length ? "Thursday works. Send a short recap." : "We'll be in touch.",
      sentiment: a.nextSteps.length ? "Positive" : "Neutral",
      tags: a.nextSteps.length ? ["next_step", "positive"] : [],
    },
  ];

  return segments.map((s, i) => ({
    ...s,
    id: `${call.id}-seg-${i}`,
    organisationId: ORG_ID,
  }));
}

export function buildMarkers(callId: string): TimelineMarker[] {
  const a = analysisByCallId[callId];
  if (!a) return [];
  const markers: TimelineMarker[] = [];
  if (a.objections.length)
    markers.push({ callId, type: "objection", atSec: 110, label: "Objection" });
  if (
    a.topics.includes("pricing") ||
    a.objections.includes("pricing") ||
    a.objections.includes("spreads")
  ) {
    markers.push({ callId, type: "pricing", atSec: 55, label: "Pricing" });
  }
  if (a.competitors.length)
    markers.push({ callId, type: "competitor", atSec: 220, label: a.competitors[0] });
  if (a.sentiment === "Positive")
    markers.push({ callId, type: "positive", atSec: 330, label: "Positive" });
  if (a.sentiment === "Negative" || a.sentiment === "Mixed") {
    markers.push({ callId, type: "negative", atSec: 160, label: "Friction" });
  }
  if (a.interruptions >= 4)
    markers.push({ callId, type: "interruption", atSec: 180, label: "Interruptions" });
  if (a.nextSteps.length)
    markers.push({ callId, type: "next_step", atSec: 270, label: "Next step" });
  if (a.weaknesses.some((w) => /compliance|disclosure/i.test(w.text))) {
    markers.push({ callId, type: "compliance", atSec: 200, label: "Compliance gap" });
  }
  return markers;
}

export const coachingItems: CoachingItem[] = [
  {
    id: "coach-01",
    organisationId: ORG_ID,
    userId: "u-03",
    managerId: "u-01",
    skill: "Value before price",
    evidence: "Pricing introduced before discovery on c-1833 and c-1815.",
    recommendation: "Assign Value Before Price playbook and review highlighted calls.",
    suggestedExercise:
      "Roleplay: prospect asks for price in the first two minutes — deflect once, then discover.",
    status: "assigned",
    dueDate: "2026-08-05",
    completedAt: null,
    impactEstimate: "High",
    relatedCallIds: ["c-1833", "c-1815"],
    progress: 25,
    notes: "Cyprus desk priority this week.",
    behaviourImproved: null,
    planId: "plan-elena",
  },
  {
    id: "coach-02",
    organisationId: ORG_ID,
    userId: "u-05",
    managerId: "u-01",
    skill: "Discovery fundamentals",
    evidence: "c-1826 and c-1816 show interruptions and missing next steps.",
    recommendation: "Complete listening drill + discovery checklist roleplay.",
    suggestedExercise: "Record a 5-question discovery checklist practice with AI roleplay.",
    status: "in_progress",
    dueDate: "2026-08-03",
    completedAt: null,
    impactEstimate: "High",
    relatedCallIds: ["c-1826", "c-1816"],
    progress: 55,
    notes: "Manager check-in scheduled Friday.",
    behaviourImproved: null,
    planId: "plan-omar",
  },
  {
    id: "coach-03",
    organisationId: ORG_ID,
    userId: "u-04",
    managerId: "u-01",
    skill: "Objection handling",
    evidence: "Price-led openers on Delta Spreads (c-1818).",
    recommendation: "Practise acknowledge → reframe → evidence pattern.",
    suggestedExercise: "Objection library: spreads — three reframes with evidence.",
    status: "suggested",
    dueDate: "2026-08-06",
    completedAt: null,
    impactEstimate: "Medium",
    relatedCallIds: ["c-1818"],
    progress: 0,
    notes: "",
    behaviourImproved: null,
    planId: "plan-andreas",
  },
  {
    id: "coach-04",
    organisationId: ORG_ID,
    userId: "u-02",
    managerId: "u-01",
    skill: "Authority confirmation",
    evidence: "Meridian FX discovery missed economic buyer (c-1813).",
    recommendation: "Add authority check to discovery stage.",
    suggestedExercise: "Script: Who else weighs in on liquidity changes?",
    status: "completed",
    dueDate: "2026-07-28",
    completedAt: "2026-07-29",
    impactEstimate: "Medium",
    relatedCallIds: ["c-1813"],
    progress: 100,
    notes: "Follow-up call confirmed economic buyer.",
    behaviourImproved: true,
    planId: "plan-priya",
  },
  {
    id: "coach-05",
    organisationId: ORG_ID,
    userId: "u-09",
    managerId: "u-08",
    skill: "Next-step discipline",
    evidence: "Two Seaside Homes calls without calendar hold.",
    recommendation: "Always book next step live before hanging up.",
    suggestedExercise: "Close every practice call with a dated calendar ask.",
    status: "assigned",
    dueDate: "2026-08-04",
    completedAt: null,
    impactEstimate: "Medium",
    relatedCallIds: ["c-1812", "c-1822"],
    progress: 10,
    notes: "",
    behaviourImproved: null,
    planId: "plan-diego",
  },
  {
    id: "coach-06",
    organisationId: ORG_ID,
    userId: "u-06",
    managerId: "u-dir",
    skill: "Competitor handling",
    evidence: "Aurora Insurance lost after unresolved RivalCo preference.",
    recommendation: "Use competitor battlecard in roleplay.",
    suggestedExercise: "Roleplay RivalCo comparison with compliance-safe language.",
    status: "in_progress",
    dueDate: "2026-08-07",
    completedAt: null,
    impactEstimate: "High",
    relatedCallIds: ["c-1838", "c-1811"],
    progress: 40,
    notes: "Battlecard attached in Knowledge.",
    behaviourImproved: null,
    planId: "plan-lena",
  },
  {
    id: "coach-07",
    organisationId: ORG_ID,
    userId: "u-03",
    managerId: "u-01",
    skill: "Discovery depth",
    evidence: "BluePeak follow-ups still light on pain quantification.",
    recommendation: "Aim for 6–8 open questions before commercial terms.",
    suggestedExercise: "Discovery framework drill — volume, pain, authority, timeline.",
    status: "suggested",
    dueDate: "2026-08-08",
    completedAt: null,
    impactEstimate: "Medium",
    relatedCallIds: ["c-1833"],
    progress: 0,
    notes: "",
    behaviourImproved: null,
    planId: "plan-elena",
  },
  {
    id: "coach-08",
    organisationId: ORG_ID,
    userId: "u-04",
    managerId: "u-01",
    skill: "Compliance disclosure",
    evidence: "Crescent Brokers call missed a required disclosure moment (c-1835).",
    recommendation: "Run disclosure checklist before every regulated product pitch.",
    suggestedExercise: "Compliance script walkthrough with manager.",
    status: "dismissed",
    dueDate: "2026-07-30",
    completedAt: null,
    impactEstimate: "High",
    relatedCallIds: ["c-1835"],
    progress: 0,
    notes: "Dismissed — duplicate of assigned checklist training.",
    behaviourImproved: null,
    planId: "plan-andreas",
  },
];

export const alerts: Alert[] = [
  {
    id: "al-01",
    organisationId: ORG_ID,
    type: "performance",
    severity: "critical",
    title: "Omar Haddad needs attention",
    description: "Multiple sub-65 scores and open discovery coaching.",
    relatedEntityId: "u-05",
    createdAt: iso("2026-07-30", "08:00"),
    resolvedAt: null,
  },
  {
    id: "al-02",
    organisationId: ORG_ID,
    type: "pipeline",
    severity: "warning",
    title: "High-risk pipeline €384K+",
    description: "Deals with High risk across Forex and Wealth.",
    relatedEntityId: null,
    createdAt: iso("2026-07-30", "07:30"),
    resolvedAt: null,
  },
  {
    id: "al-03",
    organisationId: ORG_ID,
    type: "coaching",
    severity: "info",
    title: "Cyprus desk close-rate pattern",
    description:
      "Pricing before discovery appears in 41% of recent lost/follow-up friction calls (demo insight).",
    relatedEntityId: "team-forex",
    createdAt: iso("2026-07-29", "18:00"),
    resolvedAt: null,
  },
  {
    id: "al-04",
    organisationId: ORG_ID,
    type: "compliance",
    severity: "warning",
    title: "Disclosure miss flagged",
    description: "Crescent Brokers call missed a required disclosure moment.",
    relatedEntityId: "c-1835",
    createdAt: iso("2026-07-28", "17:00"),
    resolvedAt: null,
  },
];

export const playbooks: Playbook[] = [
  {
    id: "pb-01",
    organisationId: ORG_ID,
    teamId: null,
    name: "Value Before Price",
    category: "Discovery frameworks",
    scope: "company",
    purpose: "Establish value and quantify pain before discussing commercial terms.",
    applicableCallTypes: ["Outbound", "Discovery", "Follow-up"],
    requiredBehaviours: ["Ask 6+ discovery questions", "Quantify pain", "Delay pricing"],
    recommendedPhrases: [
      "Before numbers — how many lots are you averaging monthly?",
      "What breaks when execution slips?",
    ],
    phrasesToAvoid: ["We're pretty competitive actually", "Our price is…"],
    exampleCallIds: ["c-1841", "c-1834", "c-1830"],
    adoptionScore: 62,
    impactTrend: [48, 52, 55, 58, 62],
    ownerId: "u-01",
    status: "active",
    version: 3,
  },
  {
    id: "pb-02",
    organisationId: ORG_ID,
    teamId: "team-forex",
    name: "Objection: Spreads",
    category: "Objection library",
    scope: "team",
    purpose: "Acknowledge, quantify, and reframe spread objections with execution evidence.",
    applicableCallTypes: ["Outbound", "Follow-up"],
    requiredBehaviours: ["Acknowledge", "Quantify current cost", "Reframe with fill quality"],
    recommendedPhrases: [
      "What are you paying per lot today?",
      "If we're within 0.2 but fill quality improves, does the maths still work against us?",
    ],
    phrasesToAvoid: ["Most clients don't mind"],
    exampleCallIds: ["c-1831", "c-1821"],
    adoptionScore: 71,
    impactTrend: [60, 63, 66, 69, 71],
    ownerId: "u-01",
    status: "active",
    version: 2,
  },
  {
    id: "pb-03",
    organisationId: ORG_ID,
    teamId: null,
    name: "Next-step discipline",
    category: "Closing frameworks",
    scope: "company",
    purpose: "Always leave with an owned calendar commitment.",
    applicableCallTypes: ["Outbound", "Inbound", "Follow-up", "Discovery"],
    requiredBehaviours: ["Propose specific time", "Confirm owner", "Send recap"],
    recommendedPhrases: ["Let's lock Thursday so we keep momentum — does 10:00 still work?"],
    phrasesToAvoid: ["Feel free to call me when you've decided"],
    exampleCallIds: ["c-1841", "c-1827", "c-1819"],
    adoptionScore: 58,
    impactTrend: [45, 49, 52, 55, 58],
    ownerId: "u-dir",
    status: "active",
    version: 2,
  },
  {
    id: "pb-04",
    organisationId: ORG_ID,
    teamId: null,
    name: "Disclosure checklist",
    category: "Compliance scripts",
    scope: "company",
    purpose: "Required disclosures for regulated product conversations.",
    applicableCallTypes: ["Outbound", "Discovery"],
    requiredBehaviours: ["Read required disclosure", "Confirm understanding", "Log completion"],
    recommendedPhrases: ["Before we continue, I need to share a short risk disclosure…"],
    phrasesToAvoid: ["Skipping the formal bits"],
    exampleCallIds: ["c-1834"],
    adoptionScore: 81,
    impactTrend: [70, 74, 77, 79, 81],
    ownerId: "u-admin",
    status: "active",
    version: 4,
  },
  {
    id: "pb-05",
    organisationId: ORG_ID,
    teamId: null,
    name: "Winning mutual next steps",
    category: "AI-discovered best practices",
    scope: "ai_discovered",
    purpose: "Pattern from top Closed calls: dated next step booked live.",
    applicableCallTypes: ["Outbound", "Follow-up"],
    requiredBehaviours: ["Book live", "Restate value", "Confirm attendees"],
    recommendedPhrases: ["I'll send a calendar hold before we hang up"],
    phrasesToAvoid: ["I'll wait to hear from you"],
    exampleCallIds: ["c-1841", "c-1837", "c-1819"],
    adoptionScore: 44,
    impactTrend: [30, 34, 38, 41, 44],
    ownerId: "u-exec",
    status: "draft",
    version: 1,
  },
  {
    id: "pb-06",
    organisationId: ORG_ID,
    teamId: "team-wealth",
    name: "Protection product opener",
    category: "Product-specific playbooks",
    scope: "team",
    purpose: "Needs-led opener for insurance protection conversations.",
    applicableCallTypes: ["Outbound", "Discovery"],
    requiredBehaviours: ["Map coverage gaps", "Confirm dependents", "Avoid product dump"],
    recommendedPhrases: ["What would a gap in coverage cost your clients this year?"],
    phrasesToAvoid: ["Let me walk you through all our products"],
    exampleCallIds: ["c-1811"],
    adoptionScore: 39,
    impactTrend: [28, 31, 34, 36, 39],
    ownerId: "u-06",
    status: "archived",
    version: 2,
  },
];

export const insights: Insight[] = [
  {
    id: "in-01",
    organisationId: ORG_ID,
    title: "Pricing-before-discovery pattern",
    body: "Close rates declined where pricing was introduced before sufficient discovery. Elena and Andreas show the largest gap vs top performers. Assign Value Before Price.",
    createdAt: iso("2026-07-30", "06:00"),
    scope: "team",
    teamId: "team-forex",
  },
  {
    id: "in-02",
    organisationId: ORG_ID,
    title: "Top behaviour: mutual next steps",
    body: "Closed-won calls in the seed set almost always lock a dated next step live on the call.",
    createdAt: iso("2026-07-29", "06:00"),
    scope: "org",
  },
  {
    id: "in-03",
    organisationId: ORG_ID,
    title: "Omar improvement opportunity",
    body: "Listening score and interruption rate are the primary drag. Coaching already assigned.",
    createdAt: iso("2026-07-28", "06:00"),
    scope: "user",
    userId: "u-05",
  },
];

/** Precomputed org KPIs — must match aggregations in queries.ts */
export const DEMO_LABEL = "Illustrative demo data · Apex Markets";
