/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CeoRouteImport } from './routes/ceo'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCertificationsRouteImport } from './routes/app.certifications'
import { Route as AppCoachRouteImport } from './routes/app.coach'
import { Route as AppDialerRouteImport } from './routes/app.dialer'
import { Route as AppDnaRouteImport } from './routes/app.dna'
import { Route as AppGoalsRouteImport } from './routes/app.goals'
import { Route as AppKnowledgeRouteImport } from './routes/app.knowledge'
import { Route as AppLeaderboardRouteImport } from './routes/app.leaderboard'
import { Route as AppPerformanceRouteImport } from './routes/app.performance'
import { Route as AppRoleplayRouteImport } from './routes/app.roleplay'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as CeoIndexRouteImport } from './routes/ceo.index'
import { Route as CeoAlertsRouteImport } from './routes/ceo.alerts'
import { Route as CeoComparisonRouteImport } from './routes/ceo.comparison'
import { Route as CeoInsightsRouteImport } from './routes/ceo.insights'
import { Route as CeoLeaderboardsRouteImport } from './routes/ceo.leaderboards'
import { Route as CeoRevenueRouteImport } from './routes/ceo.revenue'
import { Route as CeoTelephonyRouteImport } from './routes/ceo.telephony'
import { Route as CrmIndexRouteImport } from './routes/crm.index'
import { Route as CrmAutomationsRouteImport } from './routes/crm.automations'
import { Route as CrmContactsRouteImport } from './routes/crm.contacts'
import { Route as CrmDealRiskRouteImport } from './routes/crm.deal-risk'
import { Route as CrmPipelineRouteImport } from './routes/crm.pipeline'
import { Route as CrmTasksRouteImport } from './routes/crm.tasks'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as ManagerCoachingRouteImport } from './routes/manager.coaching'
import { Route as ManagerPlaybooksRouteImport } from './routes/manager.playbooks'
import { Route as ManagerQaRouteImport } from './routes/manager.qa'
import { Route as ApiTwilioRecordingRouteImport } from './routes/api/twilio/recording'
import { Route as ApiTwilioStatusRouteImport } from './routes/api/twilio/status'
import { Route as ApiTwilioVoiceRouteImport } from './routes/api/twilio/voice'
import { Route as AppCallsIndexRouteImport } from './routes/app.calls.index'
import { Route as AppCallsCallIdRouteImport } from './routes/app.calls.$callId'
import { Route as CeoEmployeesIndexRouteImport } from './routes/ceo.employees.index'
import { Route as CeoEmployeesEmployeeIdRouteImport } from './routes/ceo.employees.$employeeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CeoRoute = CeoRouteImport.update({
  id: '/ceo',
  path: '/ceo',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificationsRoute = AppCertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppDialerRoute = AppDialerRouteImport.update({
  id: '/dialer',
  path: '/dialer',
  getParentRoute: () => AppRoute,
} as any)
const AppDnaRoute = AppDnaRouteImport.update({
  id: '/dna',
  path: '/dna',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppRoleplayRoute = AppRoleplayRouteImport.update({
  id: '/roleplay',
  path: '/roleplay',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const CeoIndexRoute = CeoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CeoRoute,
} as any)
const CeoAlertsRoute = CeoAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => CeoRoute,
} as any)
const CeoComparisonRoute = CeoComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => CeoRoute,
} as any)
const CeoInsightsRoute = CeoInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => CeoRoute,
} as any)
const CeoLeaderboardsRoute = CeoLeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => CeoRoute,
} as any)
const CeoRevenueRoute = CeoRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => CeoRoute,
} as any)
const CeoTelephonyRoute = CeoTelephonyRouteImport.update({
  id: '/telephony',
  path: '/telephony',
  getParentRoute: () => CeoRoute,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAutomationsRoute = CrmAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => CrmRoute,
} as any)
const CrmContactsRoute = CrmContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => CrmRoute,
} as any)
const CrmDealRiskRoute = CrmDealRiskRouteImport.update({
  id: '/deal-risk',
  path: '/deal-risk',
  getParentRoute: () => CrmRoute,
} as any)
const CrmPipelineRoute = CrmPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => CrmRoute,
} as any)
const CrmTasksRoute = CrmTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => CrmRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerCoachingRoute = ManagerCoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerPlaybooksRoute = ManagerPlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerQaRoute = ManagerQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => ManagerRoute,
} as any)
const ApiTwilioRecordingRoute = ApiTwilioRecordingRouteImport.update({
  id: '/api/twilio/recording',
  path: '/api/twilio/recording',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwilioStatusRoute = ApiTwilioStatusRouteImport.update({
  id: '/api/twilio/status',
  path: '/api/twilio/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwilioVoiceRoute = ApiTwilioVoiceRouteImport.update({
  id: '/api/twilio/voice',
  path: '/api/twilio/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCallsIndexRoute = AppCallsIndexRouteImport.update({
  id: '/calls/',
  path: '/calls/',
  getParentRoute: () => AppRoute,
} as any)
const AppCallsCallIdRoute = AppCallsCallIdRouteImport.update({
  id: '/calls/$callId',
  path: '/calls/$callId',
  getParentRoute: () => AppRoute,
} as any)
const CeoEmployeesIndexRoute = CeoEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => CeoRoute,
} as any)
const CeoEmployeesEmployeeIdRoute = CeoEmployeesEmployeeIdRouteImport.update({
  id: '/employees/$employeeId',
  path: '/employees/$employeeId',
  getParentRoute: () => CeoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/ceo': typeof CeoRouteWithChildren
  '/crm': typeof CrmRouteWithChildren
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/manager': typeof ManagerRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/certifications': typeof AppCertificationsRoute
  '/app/coach': typeof AppCoachRoute
  '/app/dialer': typeof AppDialerRoute
  '/app/dna': typeof AppDnaRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/roleplay': typeof AppRoleplayRoute
  '/app/settings': typeof AppSettingsRoute
  '/ceo/alerts': typeof CeoAlertsRoute
  '/ceo/comparison': typeof CeoComparisonRoute
  '/ceo/insights': typeof CeoInsightsRoute
  '/ceo/leaderboards': typeof CeoLeaderboardsRoute
  '/ceo/revenue': typeof CeoRevenueRoute
  '/ceo/telephony': typeof CeoTelephonyRoute
  '/crm/automations': typeof CrmAutomationsRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/deal-risk': typeof CrmDealRiskRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/crm/tasks': typeof CrmTasksRoute
  '/invite/$token': typeof InviteTokenRoute
  '/manager/coaching': typeof ManagerCoachingRoute
  '/manager/playbooks': typeof ManagerPlaybooksRoute
  '/manager/qa': typeof ManagerQaRoute
  '/app/': typeof AppIndexRoute
  '/ceo/': typeof CeoIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/api/twilio/recording': typeof ApiTwilioRecordingRoute
  '/api/twilio/status': typeof ApiTwilioStatusRoute
  '/api/twilio/voice': typeof ApiTwilioVoiceRoute
  '/app/calls/$callId': typeof AppCallsCallIdRoute
  '/ceo/employees/$employeeId': typeof CeoEmployeesEmployeeIdRoute
  '/app/calls/': typeof AppCallsIndexRoute
  '/ceo/employees/': typeof CeoEmployeesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/app/certifications': typeof AppCertificationsRoute
  '/app/coach': typeof AppCoachRoute
  '/app/dialer': typeof AppDialerRoute
  '/app/dna': typeof AppDnaRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/roleplay': typeof AppRoleplayRoute
  '/app/settings': typeof AppSettingsRoute
  '/ceo/alerts': typeof CeoAlertsRoute
  '/ceo/comparison': typeof CeoComparisonRoute
  '/ceo/insights': typeof CeoInsightsRoute
  '/ceo/leaderboards': typeof CeoLeaderboardsRoute
  '/ceo/revenue': typeof CeoRevenueRoute
  '/ceo/telephony': typeof CeoTelephonyRoute
  '/crm/automations': typeof CrmAutomationsRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/deal-risk': typeof CrmDealRiskRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/crm/tasks': typeof CrmTasksRoute
  '/invite/$token': typeof InviteTokenRoute
  '/manager/coaching': typeof ManagerCoachingRoute
  '/manager/playbooks': typeof ManagerPlaybooksRoute
  '/manager/qa': typeof ManagerQaRoute
  '/app': typeof AppIndexRoute
  '/ceo': typeof CeoIndexRoute
  '/crm': typeof CrmIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/api/twilio/recording': typeof ApiTwilioRecordingRoute
  '/api/twilio/status': typeof ApiTwilioStatusRoute
  '/api/twilio/voice': typeof ApiTwilioVoiceRoute
  '/app/calls/$callId': typeof AppCallsCallIdRoute
  '/ceo/employees/$employeeId': typeof CeoEmployeesEmployeeIdRoute
  '/app/calls': typeof AppCallsIndexRoute
  '/ceo/employees': typeof CeoEmployeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/ceo': typeof CeoRouteWithChildren
  '/crm': typeof CrmRouteWithChildren
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/manager': typeof ManagerRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/certifications': typeof AppCertificationsRoute
  '/app/coach': typeof AppCoachRoute
  '/app/dialer': typeof AppDialerRoute
  '/app/dna': typeof AppDnaRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/roleplay': typeof AppRoleplayRoute
  '/app/settings': typeof AppSettingsRoute
  '/ceo/alerts': typeof CeoAlertsRoute
  '/ceo/comparison': typeof CeoComparisonRoute
  '/ceo/insights': typeof CeoInsightsRoute
  '/ceo/leaderboards': typeof CeoLeaderboardsRoute
  '/ceo/revenue': typeof CeoRevenueRoute
  '/ceo/telephony': typeof CeoTelephonyRoute
  '/crm/automations': typeof CrmAutomationsRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/deal-risk': typeof CrmDealRiskRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/crm/tasks': typeof CrmTasksRoute
  '/invite/$token': typeof InviteTokenRoute
  '/manager/coaching': typeof ManagerCoachingRoute
  '/manager/playbooks': typeof ManagerPlaybooksRoute
  '/manager/qa': typeof ManagerQaRoute
  '/app/': typeof AppIndexRoute
  '/ceo/': typeof CeoIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/api/twilio/recording': typeof ApiTwilioRecordingRoute
  '/api/twilio/status': typeof ApiTwilioStatusRoute
  '/api/twilio/voice': typeof ApiTwilioVoiceRoute
  '/app/calls/$callId': typeof AppCallsCallIdRoute
  '/ceo/employees/$employeeId': typeof CeoEmployeesEmployeeIdRoute
  '/app/calls/': typeof AppCallsIndexRoute
  '/ceo/employees/': typeof CeoEmployeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/ceo'
    | '/crm'
    | '/demo'
    | '/forgot-password'
    | '/manager'
    | '/onboarding'
    | '/app/certifications'
    | '/app/coach'
    | '/app/dialer'
    | '/app/dna'
    | '/app/goals'
    | '/app/knowledge'
    | '/app/leaderboard'
    | '/app/performance'
    | '/app/roleplay'
    | '/app/settings'
    | '/ceo/alerts'
    | '/ceo/comparison'
    | '/ceo/insights'
    | '/ceo/leaderboards'
    | '/ceo/revenue'
    | '/ceo/telephony'
    | '/crm/automations'
    | '/crm/contacts'
    | '/crm/deal-risk'
    | '/crm/pipeline'
    | '/crm/tasks'
    | '/invite/$token'
    | '/manager/coaching'
    | '/manager/playbooks'
    | '/manager/qa'
    | '/app/'
    | '/ceo/'
    | '/crm/'
    | '/manager/'
    | '/api/twilio/recording'
    | '/api/twilio/status'
    | '/api/twilio/voice'
    | '/app/calls/$callId'
    | '/ceo/employees/$employeeId'
    | '/app/calls/'
    | '/ceo/employees/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demo'
    | '/forgot-password'
    | '/onboarding'
    | '/app/certifications'
    | '/app/coach'
    | '/app/dialer'
    | '/app/dna'
    | '/app/goals'
    | '/app/knowledge'
    | '/app/leaderboard'
    | '/app/performance'
    | '/app/roleplay'
    | '/app/settings'
    | '/ceo/alerts'
    | '/ceo/comparison'
    | '/ceo/insights'
    | '/ceo/leaderboards'
    | '/ceo/revenue'
    | '/ceo/telephony'
    | '/crm/automations'
    | '/crm/contacts'
    | '/crm/deal-risk'
    | '/crm/pipeline'
    | '/crm/tasks'
    | '/invite/$token'
    | '/manager/coaching'
    | '/manager/playbooks'
    | '/manager/qa'
    | '/app'
    | '/ceo'
    | '/crm'
    | '/manager'
    | '/api/twilio/recording'
    | '/api/twilio/status'
    | '/api/twilio/voice'
    | '/app/calls/$callId'
    | '/ceo/employees/$employeeId'
    | '/app/calls'
    | '/ceo/employees'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/ceo'
    | '/crm'
    | '/demo'
    | '/forgot-password'
    | '/manager'
    | '/onboarding'
    | '/app/certifications'
    | '/app/coach'
    | '/app/dialer'
    | '/app/dna'
    | '/app/goals'
    | '/app/knowledge'
    | '/app/leaderboard'
    | '/app/performance'
    | '/app/roleplay'
    | '/app/settings'
    | '/ceo/alerts'
    | '/ceo/comparison'
    | '/ceo/insights'
    | '/ceo/leaderboards'
    | '/ceo/revenue'
    | '/ceo/telephony'
    | '/crm/automations'
    | '/crm/contacts'
    | '/crm/deal-risk'
    | '/crm/pipeline'
    | '/crm/tasks'
    | '/invite/$token'
    | '/manager/coaching'
    | '/manager/playbooks'
    | '/manager/qa'
    | '/app/'
    | '/ceo/'
    | '/crm/'
    | '/manager/'
    | '/api/twilio/recording'
    | '/api/twilio/status'
    | '/api/twilio/voice'
    | '/app/calls/$callId'
    | '/ceo/employees/$employeeId'
    | '/app/calls/'
    | '/ceo/employees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  CeoRoute: typeof CeoRouteWithChildren
  CrmRoute: typeof CrmRouteWithChildren
  DemoRoute: typeof DemoRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ManagerRoute: typeof ManagerRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiTwilioRecordingRoute: typeof ApiTwilioRecordingRoute
  ApiTwilioStatusRoute: typeof ApiTwilioStatusRoute
  ApiTwilioVoiceRoute: typeof ApiTwilioVoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceo': {
      id: '/ceo'
      path: '/ceo'
      fullPath: '/ceo'
      preLoaderRoute: typeof CeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/certifications': {
      id: '/app/certifications'
      path: '/certifications'
      fullPath: '/app/certifications'
      preLoaderRoute: typeof AppCertificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coach': {
      id: '/app/coach'
      path: '/coach'
      fullPath: '/app/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dialer': {
      id: '/app/dialer'
      path: '/dialer'
      fullPath: '/app/dialer'
      preLoaderRoute: typeof AppDialerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dna': {
      id: '/app/dna'
      path: '/dna'
      fullPath: '/app/dna'
      preLoaderRoute: typeof AppDnaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goals': {
      id: '/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/knowledge': {
      id: '/app/knowledge'
      path: '/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leaderboard': {
      id: '/app/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/performance': {
      id: '/app/performance'
      path: '/performance'
      fullPath: '/app/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roleplay': {
      id: '/app/roleplay'
      path: '/roleplay'
      fullPath: '/app/roleplay'
      preLoaderRoute: typeof AppRoleplayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/ceo/': {
      id: '/ceo/'
      path: '/'
      fullPath: '/ceo/'
      preLoaderRoute: typeof CeoIndexRouteImport
      parentRoute: typeof CeoRoute
    }
    '/ceo/alerts': {
      id: '/ceo/alerts'
      path: '/alerts'
      fullPath: '/ceo/alerts'
      preLoaderRoute: typeof CeoAlertsRouteImport
      parentRoute: typeof CeoRoute
    }
    '/ceo/comparison': {
      id: '/ceo/comparison'
      path: '/comparison'
      fullPath: '/ceo/comparison'
      preLoaderRoute: typeof CeoComparisonRouteImport
      parentRoute: typeof CeoRoute
    }
    '/ceo/insights': {
      id: '/ceo/insights'
      path: '/insights'
      fullPath: '/ceo/insights'
      preLoaderRoute: typeof CeoInsightsRouteImport
      parentRoute: typeof CeoRoute
    }
    '/ceo/leaderboards': {
      id: '/ceo/leaderboards'
      path: '/leaderboards'
      fullPath: '/ceo/leaderboards'
      preLoaderRoute: typeof CeoLeaderboardsRouteImport
      parentRoute: typeof CeoRoute
    }
    '/ceo/revenue': {
      id: '/ceo/revenue'
      path: '/revenue'
      fullPath: '/ceo/revenue'
      preLoaderRoute: typeof CeoRevenueRouteImport
      parentRoute: typeof CeoRoute
    }
    '/ceo/telephony': {
      id: '/ceo/telephony'
      path: '/telephony'
      fullPath: '/ceo/telephony'
      preLoaderRoute: typeof CeoTelephonyRouteImport
      parentRoute: typeof CeoRoute
    }
    '/crm/': {
      id: '/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/automations': {
      id: '/crm/automations'
      path: '/automations'
      fullPath: '/crm/automations'
      preLoaderRoute: typeof CrmAutomationsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/contacts': {
      id: '/crm/contacts'
      path: '/contacts'
      fullPath: '/crm/contacts'
      preLoaderRoute: typeof CrmContactsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/deal-risk': {
      id: '/crm/deal-risk'
      path: '/deal-risk'
      fullPath: '/crm/deal-risk'
      preLoaderRoute: typeof CrmDealRiskRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/pipeline': {
      id: '/crm/pipeline'
      path: '/pipeline'
      fullPath: '/crm/pipeline'
      preLoaderRoute: typeof CrmPipelineRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/tasks': {
      id: '/crm/tasks'
      path: '/tasks'
      fullPath: '/crm/tasks'
      preLoaderRoute: typeof CrmTasksRouteImport
      parentRoute: typeof CrmRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/coaching': {
      id: '/manager/coaching'
      path: '/coaching'
      fullPath: '/manager/coaching'
      preLoaderRoute: typeof ManagerCoachingRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/playbooks': {
      id: '/manager/playbooks'
      path: '/playbooks'
      fullPath: '/manager/playbooks'
      preLoaderRoute: typeof ManagerPlaybooksRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/qa': {
      id: '/manager/qa'
      path: '/qa'
      fullPath: '/manager/qa'
      preLoaderRoute: typeof ManagerQaRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/api/twilio/recording': {
      id: '/api/twilio/recording'
      path: '/api/twilio/recording'
      fullPath: '/api/twilio/recording'
      preLoaderRoute: typeof ApiTwilioRecordingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twilio/status': {
      id: '/api/twilio/status'
      path: '/api/twilio/status'
      fullPath: '/api/twilio/status'
      preLoaderRoute: typeof ApiTwilioStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twilio/voice': {
      id: '/api/twilio/voice'
      path: '/api/twilio/voice'
      fullPath: '/api/twilio/voice'
      preLoaderRoute: typeof ApiTwilioVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/calls/': {
      id: '/app/calls/'
      path: '/calls'
      fullPath: '/app/calls/'
      preLoaderRoute: typeof AppCallsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calls/$callId': {
      id: '/app/calls/$callId'
      path: '/calls/$callId'
      fullPath: '/app/calls/$callId'
      preLoaderRoute: typeof AppCallsCallIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/ceo/employees/': {
      id: '/ceo/employees/'
      path: '/employees'
      fullPath: '/ceo/employees/'
      preLoaderRoute: typeof CeoEmployeesIndexRouteImport
      parentRoute: typeof CeoRoute
    }
    '/ceo/employees/$employeeId': {
      id: '/ceo/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/ceo/employees/$employeeId'
      preLoaderRoute: typeof CeoEmployeesEmployeeIdRouteImport
      parentRoute: typeof CeoRoute
    }
  }
}

interface AppRouteChildren {
  AppCertificationsRoute: typeof AppCertificationsRoute
  AppCoachRoute: typeof AppCoachRoute
  AppDialerRoute: typeof AppDialerRoute
  AppDnaRoute: typeof AppDnaRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppRoleplayRoute: typeof AppRoleplayRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCallsCallIdRoute: typeof AppCallsCallIdRoute
  AppCallsIndexRoute: typeof AppCallsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCertificationsRoute: AppCertificationsRoute,
  AppCoachRoute: AppCoachRoute,
  AppDialerRoute: AppDialerRoute,
  AppDnaRoute: AppDnaRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppRoleplayRoute: AppRoleplayRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppCallsCallIdRoute: AppCallsCallIdRoute,
  AppCallsIndexRoute: AppCallsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CeoRouteChildren {
  CeoAlertsRoute: typeof CeoAlertsRoute
  CeoComparisonRoute: typeof CeoComparisonRoute
  CeoInsightsRoute: typeof CeoInsightsRoute
  CeoLeaderboardsRoute: typeof CeoLeaderboardsRoute
  CeoRevenueRoute: typeof CeoRevenueRoute
  CeoTelephonyRoute: typeof CeoTelephonyRoute
  CeoIndexRoute: typeof CeoIndexRoute
  CeoEmployeesEmployeeIdRoute: typeof CeoEmployeesEmployeeIdRoute
  CeoEmployeesIndexRoute: typeof CeoEmployeesIndexRoute
}

const CeoRouteChildren: CeoRouteChildren = {
  CeoAlertsRoute: CeoAlertsRoute,
  CeoComparisonRoute: CeoComparisonRoute,
  CeoInsightsRoute: CeoInsightsRoute,
  CeoLeaderboardsRoute: CeoLeaderboardsRoute,
  CeoRevenueRoute: CeoRevenueRoute,
  CeoTelephonyRoute: CeoTelephonyRoute,
  CeoIndexRoute: CeoIndexRoute,
  CeoEmployeesEmployeeIdRoute: CeoEmployeesEmployeeIdRoute,
  CeoEmployeesIndexRoute: CeoEmployeesIndexRoute,
}

const CeoRouteWithChildren = CeoRoute._addFileChildren(CeoRouteChildren)

interface CrmRouteChildren {
  CrmAutomationsRoute: typeof CrmAutomationsRoute
  CrmContactsRoute: typeof CrmContactsRoute
  CrmDealRiskRoute: typeof CrmDealRiskRoute
  CrmPipelineRoute: typeof CrmPipelineRoute
  CrmTasksRoute: typeof CrmTasksRoute
  CrmIndexRoute: typeof CrmIndexRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmAutomationsRoute: CrmAutomationsRoute,
  CrmContactsRoute: CrmContactsRoute,
  CrmDealRiskRoute: CrmDealRiskRoute,
  CrmPipelineRoute: CrmPipelineRoute,
  CrmTasksRoute: CrmTasksRoute,
  CrmIndexRoute: CrmIndexRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

interface ManagerRouteChildren {
  ManagerCoachingRoute: typeof ManagerCoachingRoute
  ManagerPlaybooksRoute: typeof ManagerPlaybooksRoute
  ManagerQaRoute: typeof ManagerQaRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerCoachingRoute: ManagerCoachingRoute,
  ManagerPlaybooksRoute: ManagerPlaybooksRoute,
  ManagerQaRoute: ManagerQaRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  CeoRoute: CeoRouteWithChildren,
  CrmRoute: CrmRouteWithChildren,
  DemoRoute: DemoRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ManagerRoute: ManagerRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiTwilioRecordingRoute: ApiTwilioRecordingRoute,
  ApiTwilioStatusRoute: ApiTwilioStatusRoute,
  ApiTwilioVoiceRoute: ApiTwilioVoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
