/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/app'
import { Route as BookDemoRouteImport } from './routes/book-demo'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CeoRouteImport } from './routes/ceo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DataProcessingRouteImport } from './routes/data-processing'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductRouteImport } from './routes/product'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCoachRouteImport } from './routes/app.coach'
import { Route as AppCoachingRouteImport } from './routes/app.coaching'
import { Route as AppGoalsRouteImport } from './routes/app.goals'
import { Route as AppIntegrationsRouteImport } from './routes/app.integrations'
import { Route as AppKnowledgeRouteImport } from './routes/app.knowledge'
import { Route as AppLeaderboardRouteImport } from './routes/app.leaderboard'
import { Route as AppPerformanceRouteImport } from './routes/app.performance'
import { Route as AppPipelineRouteImport } from './routes/app.pipeline'
import { Route as AppPlaybooksRouteImport } from './routes/app.playbooks'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppTrainingRouteImport } from './routes/app.training'
import { Route as CeoIndexRouteImport } from './routes/ceo.index'
import { Route as CeoAlertsRouteImport } from './routes/ceo.alerts'
import { Route as CeoComparisonRouteImport } from './routes/ceo.comparison'
import { Route as CeoInsightsRouteImport } from './routes/ceo.insights'
import { Route as CeoLeaderboardsRouteImport } from './routes/ceo.leaderboards'
import { Route as IndustriesCallCentresRouteImport } from './routes/industries.call-centres'
import { Route as IndustriesFinancialServicesRouteImport } from './routes/industries.financial-services'
import { Route as IndustriesForexRouteImport } from './routes/industries.forex'
import { Route as IndustriesRealEstateRouteImport } from './routes/industries.real-estate'
import { Route as SolutionsExecutivesRouteImport } from './routes/solutions.executives'
import { Route as SolutionsSalesManagersRouteImport } from './routes/solutions.sales-managers'
import { Route as SolutionsSalesRepresentativesRouteImport } from './routes/solutions.sales-representatives'
import { Route as AppCallsIndexRouteImport } from './routes/app.calls.index'
import { Route as AppCallsCallIdRouteImport } from './routes/app.calls.$callId'
import { Route as AppTeamUserIdRouteImport } from './routes/app.team.$userId'
import { Route as CeoEmployeesIndexRouteImport } from './routes/ceo.employees.index'
import { Route as CeoEmployeesEmployeeIdRouteImport } from './routes/ceo.employees.$employeeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDemoRoute = BookDemoRouteImport.update({
  id: '/book-demo',
  path: '/book-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CeoRoute = CeoRouteImport.update({
  id: '/ceo',
  path: '/ceo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DataProcessingRoute = DataProcessingRouteImport.update({
  id: '/data-processing',
  path: '/data-processing',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachingRoute = AppCoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaybooksRoute = AppPlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainingRoute = AppTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AppRoute,
} as any)
const CeoIndexRoute = CeoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CeoRoute,
} as any)
const CeoAlertsRoute = CeoAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => CeoRoute,
} as any)
const CeoComparisonRoute = CeoComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => CeoRoute,
} as any)
const CeoInsightsRoute = CeoInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => CeoRoute,
} as any)
const CeoLeaderboardsRoute = CeoLeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => CeoRoute,
} as any)
const IndustriesCallCentresRoute = IndustriesCallCentresRouteImport.update({
  id: '/industries/call-centres',
  path: '/industries/call-centres',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesFinancialServicesRoute =
  IndustriesFinancialServicesRouteImport.update({
    id: '/industries/financial-services',
    path: '/industries/financial-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesForexRoute = IndustriesForexRouteImport.update({
  id: '/industries/forex',
  path: '/industries/forex',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRealEstateRoute = IndustriesRealEstateRouteImport.update({
  id: '/industries/real-estate',
  path: '/industries/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsExecutivesRoute = SolutionsExecutivesRouteImport.update({
  id: '/executives',
  path: '/executives',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsSalesManagersRoute = SolutionsSalesManagersRouteImport.update({
  id: '/sales-managers',
  path: '/sales-managers',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsSalesRepresentativesRoute =
  SolutionsSalesRepresentativesRouteImport.update({
    id: '/sales-representatives',
    path: '/sales-representatives',
    getParentRoute: () => SolutionsRoute,
  } as any)
const AppCallsIndexRoute = AppCallsIndexRouteImport.update({
  id: '/calls/',
  path: '/calls/',
  getParentRoute: () => AppRoute,
} as any)
const AppCallsCallIdRoute = AppCallsCallIdRouteImport.update({
  id: '/calls/$callId',
  path: '/calls/$callId',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamUserIdRoute = AppTeamUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppTeamRoute,
} as any)
const CeoEmployeesIndexRoute = CeoEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => CeoRoute,
} as any)
const CeoEmployeesEmployeeIdRoute = CeoEmployeesEmployeeIdRouteImport.update({
  id: '/employees/$employeeId',
  path: '/employees/$employeeId',
  getParentRoute: () => CeoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/book-demo': typeof BookDemoRoute
  '/careers': typeof CareersRoute
  '/ceo': typeof CeoRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/data-processing': typeof DataProcessingRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/security': typeof SecurityRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/app/coach': typeof AppCoachRoute
  '/app/coaching': typeof AppCoachingRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/playbooks': typeof AppPlaybooksRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRouteWithChildren
  '/app/training': typeof AppTrainingRoute
  '/ceo/alerts': typeof CeoAlertsRoute
  '/ceo/comparison': typeof CeoComparisonRoute
  '/ceo/insights': typeof CeoInsightsRoute
  '/ceo/leaderboards': typeof CeoLeaderboardsRoute
  '/industries/call-centres': typeof IndustriesCallCentresRoute
  '/industries/financial-services': typeof IndustriesFinancialServicesRoute
  '/industries/forex': typeof IndustriesForexRoute
  '/industries/real-estate': typeof IndustriesRealEstateRoute
  '/solutions/executives': typeof SolutionsExecutivesRoute
  '/solutions/sales-managers': typeof SolutionsSalesManagersRoute
  '/solutions/sales-representatives': typeof SolutionsSalesRepresentativesRoute
  '/app/': typeof AppIndexRoute
  '/ceo/': typeof CeoIndexRoute
  '/app/calls/$callId': typeof AppCallsCallIdRoute
  '/app/team/$userId': typeof AppTeamUserIdRoute
  '/ceo/employees/$employeeId': typeof CeoEmployeesEmployeeIdRoute
  '/app/calls/': typeof AppCallsIndexRoute
  '/ceo/employees/': typeof CeoEmployeesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-demo': typeof BookDemoRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/data-processing': typeof DataProcessingRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/security': typeof SecurityRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/app/coach': typeof AppCoachRoute
  '/app/coaching': typeof AppCoachingRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/playbooks': typeof AppPlaybooksRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRouteWithChildren
  '/app/training': typeof AppTrainingRoute
  '/ceo/alerts': typeof CeoAlertsRoute
  '/ceo/comparison': typeof CeoComparisonRoute
  '/ceo/insights': typeof CeoInsightsRoute
  '/ceo/leaderboards': typeof CeoLeaderboardsRoute
  '/industries/call-centres': typeof IndustriesCallCentresRoute
  '/industries/financial-services': typeof IndustriesFinancialServicesRoute
  '/industries/forex': typeof IndustriesForexRoute
  '/industries/real-estate': typeof IndustriesRealEstateRoute
  '/solutions/executives': typeof SolutionsExecutivesRoute
  '/solutions/sales-managers': typeof SolutionsSalesManagersRoute
  '/solutions/sales-representatives': typeof SolutionsSalesRepresentativesRoute
  '/app': typeof AppIndexRoute
  '/ceo': typeof CeoIndexRoute
  '/app/calls/$callId': typeof AppCallsCallIdRoute
  '/app/team/$userId': typeof AppTeamUserIdRoute
  '/ceo/employees/$employeeId': typeof CeoEmployeesEmployeeIdRoute
  '/app/calls': typeof AppCallsIndexRoute
  '/ceo/employees': typeof CeoEmployeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/book-demo': typeof BookDemoRoute
  '/careers': typeof CareersRoute
  '/ceo': typeof CeoRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/data-processing': typeof DataProcessingRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/security': typeof SecurityRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/app/coach': typeof AppCoachRoute
  '/app/coaching': typeof AppCoachingRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/playbooks': typeof AppPlaybooksRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRouteWithChildren
  '/app/training': typeof AppTrainingRoute
  '/ceo/alerts': typeof CeoAlertsRoute
  '/ceo/comparison': typeof CeoComparisonRoute
  '/ceo/insights': typeof CeoInsightsRoute
  '/ceo/leaderboards': typeof CeoLeaderboardsRoute
  '/industries/call-centres': typeof IndustriesCallCentresRoute
  '/industries/financial-services': typeof IndustriesFinancialServicesRoute
  '/industries/forex': typeof IndustriesForexRoute
  '/industries/real-estate': typeof IndustriesRealEstateRoute
  '/solutions/executives': typeof SolutionsExecutivesRoute
  '/solutions/sales-managers': typeof SolutionsSalesManagersRoute
  '/solutions/sales-representatives': typeof SolutionsSalesRepresentativesRoute
  '/app/': typeof AppIndexRoute
  '/ceo/': typeof CeoIndexRoute
  '/app/calls/$callId': typeof AppCallsCallIdRoute
  '/app/team/$userId': typeof AppTeamUserIdRoute
  '/ceo/employees/$employeeId': typeof CeoEmployeesEmployeeIdRoute
  '/app/calls/': typeof AppCallsIndexRoute
  '/ceo/employees/': typeof CeoEmployeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/book-demo'
    | '/careers'
    | '/ceo'
    | '/contact'
    | '/cookies'
    | '/data-processing'
    | '/integrations'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/product'
    | '/security'
    | '/solutions'
    | '/terms'
    | '/app/coach'
    | '/app/coaching'
    | '/app/goals'
    | '/app/integrations'
    | '/app/knowledge'
    | '/app/leaderboard'
    | '/app/performance'
    | '/app/pipeline'
    | '/app/playbooks'
    | '/app/reports'
    | '/app/settings'
    | '/app/team'
    | '/app/training'
    | '/ceo/alerts'
    | '/ceo/comparison'
    | '/ceo/insights'
    | '/ceo/leaderboards'
    | '/industries/call-centres'
    | '/industries/financial-services'
    | '/industries/forex'
    | '/industries/real-estate'
    | '/solutions/executives'
    | '/solutions/sales-managers'
    | '/solutions/sales-representatives'
    | '/app/'
    | '/ceo/'
    | '/app/calls/$callId'
    | '/app/team/$userId'
    | '/ceo/employees/$employeeId'
    | '/app/calls/'
    | '/ceo/employees/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book-demo'
    | '/careers'
    | '/contact'
    | '/cookies'
    | '/data-processing'
    | '/integrations'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/product'
    | '/security'
    | '/solutions'
    | '/terms'
    | '/app/coach'
    | '/app/coaching'
    | '/app/goals'
    | '/app/integrations'
    | '/app/knowledge'
    | '/app/leaderboard'
    | '/app/performance'
    | '/app/pipeline'
    | '/app/playbooks'
    | '/app/reports'
    | '/app/settings'
    | '/app/team'
    | '/app/training'
    | '/ceo/alerts'
    | '/ceo/comparison'
    | '/ceo/insights'
    | '/ceo/leaderboards'
    | '/industries/call-centres'
    | '/industries/financial-services'
    | '/industries/forex'
    | '/industries/real-estate'
    | '/solutions/executives'
    | '/solutions/sales-managers'
    | '/solutions/sales-representatives'
    | '/app'
    | '/ceo'
    | '/app/calls/$callId'
    | '/app/team/$userId'
    | '/ceo/employees/$employeeId'
    | '/app/calls'
    | '/ceo/employees'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/book-demo'
    | '/careers'
    | '/ceo'
    | '/contact'
    | '/cookies'
    | '/data-processing'
    | '/integrations'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/product'
    | '/security'
    | '/solutions'
    | '/terms'
    | '/app/coach'
    | '/app/coaching'
    | '/app/goals'
    | '/app/integrations'
    | '/app/knowledge'
    | '/app/leaderboard'
    | '/app/performance'
    | '/app/pipeline'
    | '/app/playbooks'
    | '/app/reports'
    | '/app/settings'
    | '/app/team'
    | '/app/training'
    | '/ceo/alerts'
    | '/ceo/comparison'
    | '/ceo/insights'
    | '/ceo/leaderboards'
    | '/industries/call-centres'
    | '/industries/financial-services'
    | '/industries/forex'
    | '/industries/real-estate'
    | '/solutions/executives'
    | '/solutions/sales-managers'
    | '/solutions/sales-representatives'
    | '/app/'
    | '/ceo/'
    | '/app/calls/$callId'
    | '/app/team/$userId'
    | '/ceo/employees/$employeeId'
    | '/app/calls/'
    | '/ceo/employees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  BookDemoRoute: typeof BookDemoRoute
  CareersRoute: typeof CareersRoute
  CeoRoute: typeof CeoRouteWithChildren
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DataProcessingRoute: typeof DataProcessingRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductRoute: typeof ProductRoute
  SecurityRoute: typeof SecurityRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  TermsRoute: typeof TermsRoute
  IndustriesCallCentresRoute: typeof IndustriesCallCentresRoute
  IndustriesFinancialServicesRoute: typeof IndustriesFinancialServicesRoute
  IndustriesForexRoute: typeof IndustriesForexRoute
  IndustriesRealEstateRoute: typeof IndustriesRealEstateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-demo': {
      id: '/book-demo'
      path: '/book-demo'
      fullPath: '/book-demo'
      preLoaderRoute: typeof BookDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceo': {
      id: '/ceo'
      path: '/ceo'
      fullPath: '/ceo'
      preLoaderRoute: typeof CeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-processing': {
      id: '/data-processing'
      path: '/data-processing'
      fullPath: '/data-processing'
      preLoaderRoute: typeof DataProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coach': {
      id: '/app/coach'
      path: '/coach'
      fullPath: '/app/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coaching': {
      id: '/app/coaching'
      path: '/coaching'
      fullPath: '/app/coaching'
      preLoaderRoute: typeof AppCoachingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goals': {
      id: '/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integrations': {
      id: '/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/knowledge': {
      id: '/app/knowledge'
      path: '/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leaderboard': {
      id: '/app/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/performance': {
      id: '/app/performance'
      path: '/performance'
      fullPath: '/app/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pipeline': {
      id: '/app/pipeline'
      path: '/pipeline'
      fullPath: '/app/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/playbooks': {
      id: '/app/playbooks'
      path: '/playbooks'
      fullPath: '/app/playbooks'
      preLoaderRoute: typeof AppPlaybooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/training': {
      id: '/app/training'
      path: '/training'
      fullPath: '/app/training'
      preLoaderRoute: typeof AppTrainingRouteImport
      parentRoute: typeof AppRoute
    }
    '/ceo/': {
      id: '/ceo/'
      path: '/'
      fullPath: '/ceo/'
      preLoaderRoute: typeof CeoIndexRouteImport
      parentRoute: typeof CeoRoute
    }
    '/ceo/alerts': {
      id: '/ceo/alerts'
      path: '/alerts'
      fullPath: '/ceo/alerts'
      preLoaderRoute: typeof CeoAlertsRouteImport
      parentRoute: typeof CeoRoute
    }
    '/ceo/comparison': {
      id: '/ceo/comparison'
      path: '/comparison'
      fullPath: '/ceo/comparison'
      preLoaderRoute: typeof CeoComparisonRouteImport
      parentRoute: typeof CeoRoute
    }
    '/ceo/insights': {
      id: '/ceo/insights'
      path: '/insights'
      fullPath: '/ceo/insights'
      preLoaderRoute: typeof CeoInsightsRouteImport
      parentRoute: typeof CeoRoute
    }
    '/ceo/leaderboards': {
      id: '/ceo/leaderboards'
      path: '/leaderboards'
      fullPath: '/ceo/leaderboards'
      preLoaderRoute: typeof CeoLeaderboardsRouteImport
      parentRoute: typeof CeoRoute
    }
    '/industries/call-centres': {
      id: '/industries/call-centres'
      path: '/industries/call-centres'
      fullPath: '/industries/call-centres'
      preLoaderRoute: typeof IndustriesCallCentresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/financial-services': {
      id: '/industries/financial-services'
      path: '/industries/financial-services'
      fullPath: '/industries/financial-services'
      preLoaderRoute: typeof IndustriesFinancialServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/forex': {
      id: '/industries/forex'
      path: '/industries/forex'
      fullPath: '/industries/forex'
      preLoaderRoute: typeof IndustriesForexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/real-estate': {
      id: '/industries/real-estate'
      path: '/industries/real-estate'
      fullPath: '/industries/real-estate'
      preLoaderRoute: typeof IndustriesRealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/executives': {
      id: '/solutions/executives'
      path: '/executives'
      fullPath: '/solutions/executives'
      preLoaderRoute: typeof SolutionsExecutivesRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/sales-managers': {
      id: '/solutions/sales-managers'
      path: '/sales-managers'
      fullPath: '/solutions/sales-managers'
      preLoaderRoute: typeof SolutionsSalesManagersRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/sales-representatives': {
      id: '/solutions/sales-representatives'
      path: '/sales-representatives'
      fullPath: '/solutions/sales-representatives'
      preLoaderRoute: typeof SolutionsSalesRepresentativesRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/app/calls/': {
      id: '/app/calls/'
      path: '/calls'
      fullPath: '/app/calls/'
      preLoaderRoute: typeof AppCallsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calls/$callId': {
      id: '/app/calls/$callId'
      path: '/calls/$callId'
      fullPath: '/app/calls/$callId'
      preLoaderRoute: typeof AppCallsCallIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team/$userId': {
      id: '/app/team/$userId'
      path: '/$userId'
      fullPath: '/app/team/$userId'
      preLoaderRoute: typeof AppTeamUserIdRouteImport
      parentRoute: typeof AppTeamRoute
    }
    '/ceo/employees/': {
      id: '/ceo/employees/'
      path: '/employees'
      fullPath: '/ceo/employees/'
      preLoaderRoute: typeof CeoEmployeesIndexRouteImport
      parentRoute: typeof CeoRoute
    }
    '/ceo/employees/$employeeId': {
      id: '/ceo/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/ceo/employees/$employeeId'
      preLoaderRoute: typeof CeoEmployeesEmployeeIdRouteImport
      parentRoute: typeof CeoRoute
    }
  }
}

interface AppTeamRouteChildren {
  AppTeamUserIdRoute: typeof AppTeamUserIdRoute
}

const AppTeamRouteChildren: AppTeamRouteChildren = {
  AppTeamUserIdRoute: AppTeamUserIdRoute,
}

const AppTeamRouteWithChildren =
  AppTeamRoute._addFileChildren(AppTeamRouteChildren)

interface AppRouteChildren {
  AppCoachRoute: typeof AppCoachRoute
  AppCoachingRoute: typeof AppCoachingRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppPlaybooksRoute: typeof AppPlaybooksRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRouteWithChildren
  AppTrainingRoute: typeof AppTrainingRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCallsCallIdRoute: typeof AppCallsCallIdRoute
  AppCallsIndexRoute: typeof AppCallsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCoachRoute: AppCoachRoute,
  AppCoachingRoute: AppCoachingRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppPlaybooksRoute: AppPlaybooksRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRouteWithChildren,
  AppTrainingRoute: AppTrainingRoute,
  AppIndexRoute: AppIndexRoute,
  AppCallsCallIdRoute: AppCallsCallIdRoute,
  AppCallsIndexRoute: AppCallsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CeoRouteChildren {
  CeoAlertsRoute: typeof CeoAlertsRoute
  CeoComparisonRoute: typeof CeoComparisonRoute
  CeoInsightsRoute: typeof CeoInsightsRoute
  CeoLeaderboardsRoute: typeof CeoLeaderboardsRoute
  CeoIndexRoute: typeof CeoIndexRoute
  CeoEmployeesEmployeeIdRoute: typeof CeoEmployeesEmployeeIdRoute
  CeoEmployeesIndexRoute: typeof CeoEmployeesIndexRoute
}

const CeoRouteChildren: CeoRouteChildren = {
  CeoAlertsRoute: CeoAlertsRoute,
  CeoComparisonRoute: CeoComparisonRoute,
  CeoInsightsRoute: CeoInsightsRoute,
  CeoLeaderboardsRoute: CeoLeaderboardsRoute,
  CeoIndexRoute: CeoIndexRoute,
  CeoEmployeesEmployeeIdRoute: CeoEmployeesEmployeeIdRoute,
  CeoEmployeesIndexRoute: CeoEmployeesIndexRoute,
}

const CeoRouteWithChildren = CeoRoute._addFileChildren(CeoRouteChildren)

interface SolutionsRouteChildren {
  SolutionsExecutivesRoute: typeof SolutionsExecutivesRoute
  SolutionsSalesManagersRoute: typeof SolutionsSalesManagersRoute
  SolutionsSalesRepresentativesRoute: typeof SolutionsSalesRepresentativesRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsExecutivesRoute: SolutionsExecutivesRoute,
  SolutionsSalesManagersRoute: SolutionsSalesManagersRoute,
  SolutionsSalesRepresentativesRoute: SolutionsSalesRepresentativesRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  BookDemoRoute: BookDemoRoute,
  CareersRoute: CareersRoute,
  CeoRoute: CeoRouteWithChildren,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DataProcessingRoute: DataProcessingRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProductRoute: ProductRoute,
  SecurityRoute: SecurityRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  TermsRoute: TermsRoute,
  IndustriesCallCentresRoute: IndustriesCallCentresRoute,
  IndustriesFinancialServicesRoute: IndustriesFinancialServicesRoute,
  IndustriesForexRoute: IndustriesForexRoute,
  IndustriesRealEstateRoute: IndustriesRealEstateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
