/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as CeoRouteImport } from './routes/ceo'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCoachRouteImport } from './routes/app.coach'
import { Route as AppGoalsRouteImport } from './routes/app.goals'
import { Route as AppLeaderboardRouteImport } from './routes/app.leaderboard'
import { Route as AppPerformanceRouteImport } from './routes/app.performance'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as CeoIndexRouteImport } from './routes/ceo.index'
import { Route as CeoAlertsRouteImport } from './routes/ceo.alerts'
import { Route as CeoComparisonRouteImport } from './routes/ceo.comparison'
import { Route as CeoInsightsRouteImport } from './routes/ceo.insights'
import { Route as CeoLeaderboardsRouteImport } from './routes/ceo.leaderboards'
import { Route as AppCallsIndexRouteImport } from './routes/app.calls.index'
import { Route as AppCallsCallIdRouteImport } from './routes/app.calls.$callId'
import { Route as CeoEmployeesIndexRouteImport } from './routes/ceo.employees.index'
import { Route as CeoEmployeesEmployeeIdRouteImport } from './routes/ceo.employees.$employeeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CeoRoute = CeoRouteImport.update({
  id: '/ceo',
  path: '/ceo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const CeoIndexRoute = CeoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CeoRoute,
} as any)
const CeoAlertsRoute = CeoAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => CeoRoute,
} as any)
const CeoComparisonRoute = CeoComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => CeoRoute,
} as any)
const CeoInsightsRoute = CeoInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => CeoRoute,
} as any)
const CeoLeaderboardsRoute = CeoLeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => CeoRoute,
} as any)
const AppCallsIndexRoute = AppCallsIndexRouteImport.update({
  id: '/calls/',
  path: '/calls/',
  getParentRoute: () => AppRoute,
} as any)
const AppCallsCallIdRoute = AppCallsCallIdRouteImport.update({
  id: '/calls/$callId',
  path: '/calls/$callId',
  getParentRoute: () => AppRoute,
} as any)
const CeoEmployeesIndexRoute = CeoEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => CeoRoute,
} as any)
const CeoEmployeesEmployeeIdRoute = CeoEmployeesEmployeeIdRouteImport.update({
  id: '/employees/$employeeId',
  path: '/employees/$employeeId',
  getParentRoute: () => CeoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/ceo': typeof CeoRouteWithChildren
  '/app/coach': typeof AppCoachRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/settings': typeof AppSettingsRoute
  '/ceo/alerts': typeof CeoAlertsRoute
  '/ceo/comparison': typeof CeoComparisonRoute
  '/ceo/insights': typeof CeoInsightsRoute
  '/ceo/leaderboards': typeof CeoLeaderboardsRoute
  '/app/': typeof AppIndexRoute
  '/ceo/': typeof CeoIndexRoute
  '/app/calls/$callId': typeof AppCallsCallIdRoute
  '/ceo/employees/$employeeId': typeof CeoEmployeesEmployeeIdRoute
  '/app/calls/': typeof AppCallsIndexRoute
  '/ceo/employees/': typeof CeoEmployeesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/coach': typeof AppCoachRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/settings': typeof AppSettingsRoute
  '/ceo/alerts': typeof CeoAlertsRoute
  '/ceo/comparison': typeof CeoComparisonRoute
  '/ceo/insights': typeof CeoInsightsRoute
  '/ceo/leaderboards': typeof CeoLeaderboardsRoute
  '/app': typeof AppIndexRoute
  '/ceo': typeof CeoIndexRoute
  '/app/calls/$callId': typeof AppCallsCallIdRoute
  '/ceo/employees/$employeeId': typeof CeoEmployeesEmployeeIdRoute
  '/app/calls': typeof AppCallsIndexRoute
  '/ceo/employees': typeof CeoEmployeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/ceo': typeof CeoRouteWithChildren
  '/app/coach': typeof AppCoachRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/settings': typeof AppSettingsRoute
  '/ceo/alerts': typeof CeoAlertsRoute
  '/ceo/comparison': typeof CeoComparisonRoute
  '/ceo/insights': typeof CeoInsightsRoute
  '/ceo/leaderboards': typeof CeoLeaderboardsRoute
  '/app/': typeof AppIndexRoute
  '/ceo/': typeof CeoIndexRoute
  '/app/calls/$callId': typeof AppCallsCallIdRoute
  '/ceo/employees/$employeeId': typeof CeoEmployeesEmployeeIdRoute
  '/app/calls/': typeof AppCallsIndexRoute
  '/ceo/employees/': typeof CeoEmployeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/ceo'
    | '/app/coach'
    | '/app/goals'
    | '/app/leaderboard'
    | '/app/performance'
    | '/app/settings'
    | '/ceo/alerts'
    | '/ceo/comparison'
    | '/ceo/insights'
    | '/ceo/leaderboards'
    | '/app/'
    | '/ceo/'
    | '/app/calls/$callId'
    | '/ceo/employees/$employeeId'
    | '/app/calls/'
    | '/ceo/employees/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/coach'
    | '/app/goals'
    | '/app/leaderboard'
    | '/app/performance'
    | '/app/settings'
    | '/ceo/alerts'
    | '/ceo/comparison'
    | '/ceo/insights'
    | '/ceo/leaderboards'
    | '/app'
    | '/ceo'
    | '/app/calls/$callId'
    | '/ceo/employees/$employeeId'
    | '/app/calls'
    | '/ceo/employees'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/ceo'
    | '/app/coach'
    | '/app/goals'
    | '/app/leaderboard'
    | '/app/performance'
    | '/app/settings'
    | '/ceo/alerts'
    | '/ceo/comparison'
    | '/ceo/insights'
    | '/ceo/leaderboards'
    | '/app/'
    | '/ceo/'
    | '/app/calls/$callId'
    | '/ceo/employees/$employeeId'
    | '/app/calls/'
    | '/ceo/employees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CeoRoute: typeof CeoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceo': {
      id: '/ceo'
      path: '/ceo'
      fullPath: '/ceo'
      preLoaderRoute: typeof CeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coach': {
      id: '/app/coach'
      path: '/coach'
      fullPath: '/app/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goals': {
      id: '/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leaderboard': {
      id: '/app/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/performance': {
      id: '/app/performance'
      path: '/performance'
      fullPath: '/app/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/ceo/': {
      id: '/ceo/'
      path: '/'
      fullPath: '/ceo/'
      preLoaderRoute: typeof CeoIndexRouteImport
      parentRoute: typeof CeoRoute
    }
    '/ceo/alerts': {
      id: '/ceo/alerts'
      path: '/alerts'
      fullPath: '/ceo/alerts'
      preLoaderRoute: typeof CeoAlertsRouteImport
      parentRoute: typeof CeoRoute
    }
    '/ceo/comparison': {
      id: '/ceo/comparison'
      path: '/comparison'
      fullPath: '/ceo/comparison'
      preLoaderRoute: typeof CeoComparisonRouteImport
      parentRoute: typeof CeoRoute
    }
    '/ceo/insights': {
      id: '/ceo/insights'
      path: '/insights'
      fullPath: '/ceo/insights'
      preLoaderRoute: typeof CeoInsightsRouteImport
      parentRoute: typeof CeoRoute
    }
    '/ceo/leaderboards': {
      id: '/ceo/leaderboards'
      path: '/leaderboards'
      fullPath: '/ceo/leaderboards'
      preLoaderRoute: typeof CeoLeaderboardsRouteImport
      parentRoute: typeof CeoRoute
    }
    '/app/calls/': {
      id: '/app/calls/'
      path: '/calls'
      fullPath: '/app/calls/'
      preLoaderRoute: typeof AppCallsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calls/$callId': {
      id: '/app/calls/$callId'
      path: '/calls/$callId'
      fullPath: '/app/calls/$callId'
      preLoaderRoute: typeof AppCallsCallIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/ceo/employees/': {
      id: '/ceo/employees/'
      path: '/employees'
      fullPath: '/ceo/employees/'
      preLoaderRoute: typeof CeoEmployeesIndexRouteImport
      parentRoute: typeof CeoRoute
    }
    '/ceo/employees/$employeeId': {
      id: '/ceo/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/ceo/employees/$employeeId'
      preLoaderRoute: typeof CeoEmployeesEmployeeIdRouteImport
      parentRoute: typeof CeoRoute
    }
  }
}

interface AppRouteChildren {
  AppCoachRoute: typeof AppCoachRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCallsCallIdRoute: typeof AppCallsCallIdRoute
  AppCallsIndexRoute: typeof AppCallsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCoachRoute: AppCoachRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppCallsCallIdRoute: AppCallsCallIdRoute,
  AppCallsIndexRoute: AppCallsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CeoRouteChildren {
  CeoAlertsRoute: typeof CeoAlertsRoute
  CeoComparisonRoute: typeof CeoComparisonRoute
  CeoInsightsRoute: typeof CeoInsightsRoute
  CeoLeaderboardsRoute: typeof CeoLeaderboardsRoute
  CeoIndexRoute: typeof CeoIndexRoute
  CeoEmployeesEmployeeIdRoute: typeof CeoEmployeesEmployeeIdRoute
  CeoEmployeesIndexRoute: typeof CeoEmployeesIndexRoute
}

const CeoRouteChildren: CeoRouteChildren = {
  CeoAlertsRoute: CeoAlertsRoute,
  CeoComparisonRoute: CeoComparisonRoute,
  CeoInsightsRoute: CeoInsightsRoute,
  CeoLeaderboardsRoute: CeoLeaderboardsRoute,
  CeoIndexRoute: CeoIndexRoute,
  CeoEmployeesEmployeeIdRoute: CeoEmployeesEmployeeIdRoute,
  CeoEmployeesIndexRoute: CeoEmployeesIndexRoute,
}

const CeoRouteWithChildren = CeoRoute._addFileChildren(CeoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CeoRoute: CeoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
